### ISSUE TITLE
给群里的其他人（非好友）发送私聊消息不成功

### ISSUE THREAD

**Issue by sxyandapp** [richardchien/coolq-http-api#10]
给群里的其他人（非好友）发送私聊消息不成功，不知道是http-api的问题还是cuq目前不支持。目前的测试结果是只能接收到别人通过群发送过来的私聊消息，但是无法发送私聊消息。

**Comment by richardchien** [comment]
我这边测试的时候是，必须接收到过对方的临时消息，才能成功发回去，这应该是酷 Q 目前不支持。

**Comment by sxyandapp** [comment]
我测试的是即使接收过对方的临时消息，也发送不成功（发送之后对方没有收到任何消息）

**Comment by richardchien** [comment]
酷 Q 的日志说什么呢（应该是找不到好友关系之类的吧）

**Comment by sxyandapp** [comment]
刚试了下，居然可以了。对了，我是刚刚把酷q登录的账号从好友里删除了，而且没有重启酷q，难道必须重启才可以？

**Comment by richardchien** [comment]
也许有可能吧。那我关闭这个 issue 了

**Comment by sxyandapp** [comment]
刚刚重新测试了下，在日志里看都是正常的，能正常发送消息，但是对方确实受不到，重启酷q后就可以了。先不管了，反正也不是什么大的bug

**Comment by richardchien** [comment]
还有一个要注意的是，似乎有时候 QQ 会莫名其妙屏蔽掉某人的临时会话，需要手动取消屏蔽一下，不确定你那边是不是因为这个。另外酷 Q 确实有时候也是坑，有一些发送不出去的情况它不提示，显示正常发送，其实没发出去。因为我这个程序只是直接调用酷 Q SDK 对应的接口，所以这种情况多半是酷 Q 的毛病
