### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Nixiabing** [richardchien/coolq-http-api#103]
我在一台阿里云上部署了docker，正常用novnc登录了酷Q，然后我往应用管理里面添加了http api的插件，也启用了，但服务器上5700的端口没有被正常使用，所以不能进行http通信。
求助这是怎么回事？

**Comment by richardchien** [comment]
你 docker 的启动命令是怎么写的呢，暴露了 5700 端口吗

**Comment by Nixiabing** [comment]
docker run --name=coolq -d -p 9001:9000 -v /home/coolq-data:/home/user/coolq -e VNC_PASSWD=323122 -e COOLQ_ACCOUNT=1399827297 coolq/wine-coolq

**Comment by Nixiabing** [comment]
插件放进去后 还要自己手动开5700端口，是这样嘛？
我以为是 插件开启后自动会启用5700的，服务器目前没监听5700端口。

**Comment by richardchien** [comment]
插件在容器里面会默认监听5700，但你要在宿主机访问他，还必须用 -p 参数把5700绑定到宿主机的端口，就像你现在的 -p 9001:9000 一样
Nixiabing <notifications@github.com>于2018年8月6日 周一07:59写道：

**Comment by Nixiabing** [comment]
已解决，谢谢。
