### ISSUE TITLE
无法发送讨论组消息

### ISSUE THREAD

**Issue by ljfuyuan** [richardchien/coolq-http-api#105]
插件版本：4.3.1
使用的docker richardchien/cqhttp:latest
send_discuss_msg 返回-38错误  在日志里看到，ID：1829 错误：发送失败（接收者帐号错误或帐号不在该群组内） (-38)

但实际上从日志里提取的讨论组ID是正确的，是我哪弄错了么？

**Comment by ljfuyuan** [comment]
好吧，我已经解决了，直接用send_group_msg 的api来发就可以了。@richardchien看看是不是bug什么的。

**Comment by richardchien** [comment]
现在 QQ 新拉的讨论组其实全部都是群，有可能是这个原因
