### ISSUE TITLE
post_url不生效

### ISSUE THREAD

**Issue by fa-ge** [richardchien/coolq-http-api#107]
运行环境 
mac os 10.13.1
Docker version 18.06.0-ce

命令  docker run -ti --rm --name cqhttp-test -v $(pwd)/coolq:/home/user/coolq -p 9000:9000 -p 5700:5700 -e COOLQ_ACCOUNT=qq号 -e CQHTTP_POST_URL=http://127.0.0.1:8081 richardchien/cqhttp:latest

通过127.0.0.1:9000站点登录qq，日志上没有报错。一切正常
![50d3a85b-6153-4973-956c-dc9e963f1ea9](https://user-images.githubusercontent.com/6771881/44311543-e225cb00-a41b-11e8-8162-6c5b9d42e072.png)

能正常使用 http://127.0.0.1:5700/send_private_msg 等api

本地起了一个监听8081端口的server，
`
const Koa = require('koa');
const app = new Koa();

app.use(async ctx => {
    console.log(133);
  ctx.body = 'Hello World';
});

app.listen(8081);
`
浏览器访问这个server没问题。但是并没有看到有任何请求来访问这个server。是我对post_url的理解有问题吗？coolq-http-api不是应该在qq接受到消息的时候访问我这个server吗？

**Comment by richardchien** [comment]
docker 容器里面不能直接通过 127.0.0.1 访问宿主机，现在插件最新版的日志不会写入到酷 Q 的日志窗口，可以到 `app\io.github.richardchien.coolqhttpapi\log\` 里面查看。

你可以让 Koa 监听 `172.17.0.1`（docker 的默认网桥上宿主机的 IP），然后 `post_url` 用这个 IP，或者，docker run 的时候加 `--network=host` 参数，直接使用宿主机的网络（macOS 上用不了）

**Comment by Ray-Eldath** [comment]
解决了吗... 我好像没搞好啊...
`docker run`: 
```bash
> docker run -ti --rm --name cqhttp-test -v ./coolq:/home/user/coolq -p 9000:9000 -p 5700:5700 -e COOLQ_ACCOUNT=1464443139 -e CQHTTP_POST_URL==http://172.17.0.1:5800 -e CQHTTP_SERVE_DATA_FILES=yes richardchien/cqhttp:latest
```
Koa:
```javascript
import * as Koa from "koa";

const app = new Koa();

app.use(async ctx => {
  ctx.body = "Hello World!";
  console.log("One client connect!");
});

app.listen(5800, "172.17.0.1");
```

**Comment by richardchien** [comment]
> http://172.17.0.1:5800

这个 IP，你需要看看你机器上的 Docker 到底用的是哪个，需要 `docker inspect bridge` 可以看到，或者使用宿主机的 `ipconfig`（Windows）或 `ifconfig`（*nix）来查看

**Comment by Ray-Eldath** [comment]
似乎还是不行... `ipconfig` 返回的地址是 `以太网适配器 vEthernet (DockerNAT) - IPv4 地址: 10.0.75.1`，然后主机监听 `http://localhost:5800` 地址，使用以下指令启动 container：
```bash
$ docker run -ti --rm --name cqhttp-test -v G:\coolq:/home/user/coolq -p 9000:9000 -p 5700:5700 -p 5800:5800 -e COOLQ_ACCOUNT=3101458826 -e CQHTTP_POST_URL=http://10.0.75.1:5800 -e CQHTTP_SERVE_DATA=yes richardchien/cqhttp:latest
```
依然不行... 主机无法监听到。日志文件中有：
```
[2018-09-02 04:15:46.733] [W] [HTTP] HTTP 上报地址 http://10.0.75.1:5800 无法访问
```

**Comment by ma6254** [comment]
@Ray-Eldath --netowork host 即是了
