### ISSUE TITLE
获取群成员列表 失败、发送好友赞 失败

### ISSUE THREAD

**Issue by PrintNow** [richardchien/coolq-http-api#110]
##  1. *获取群成员列表* 失败
- 请求 URL：`http://127.0.0.1:5700/get_group_member_list?group_id=群号码`
- **机器人已加入该群**

返回结果：
```
{
    "data": null,
    "retcode": 102,
    "status": "failed"
}
````

##  2. *发送好友赞* 失败
- 请求 URL：`http://127.0.0.1:5700/send_like?user_id=QQ号&times=10`
- **机器人添加了需要点赞的好友**

返回结果：
```
{
    "data": null,
    "retcode": -99,
    "status": "failed"
}
````

---

### 不知道是不是协议失效了还是

**Comment by richardchien** [comment]
第一个是酷 Q 的 cookie 可能出了点问题，重启酷 Q 试试

第二个是因为点赞需要酷 Q Pro

**Comment by PrintNow** [comment]
好的，已经解决，谢谢！
