### ISSUE TITLE
关于图片上传失败的问题

### ISSUE THREAD

**Issue by b02033147** [richardchien/coolq-http-api#111]
首先感谢大神代码的无私分享，真的帮助良多。我在使用过程中经常遇到一个问题，报送网络图片消息时，有时会发送不了图片，查看酷q pro日志是这样的提示：

ID	time	priority	source	name	detail
30380	1535511659	10	酷Q	[↑]图片	图片上传失败 (36533a4e0e7c780b6da39834192cc889.tmp)

请问你这边有遇到过吗？
这个问题不是肯定发生，就是有那么小概率。而且怪就怪在如果删掉酷Q image里的缓存内容，再次调试信息，很大概率不会失败。
关于消息内容格式应该没有问题的，毕竟大多数都能发成功，数组格式和字符串CQ码格式都试过，好像并没有影响。
我使用的api版本是4.3.1，酷Q版本是5.11Pro。
曾经失败过的网络图片如：
https://nos.netease.com/nim/NDA5MzEwOA==/bmltYV8xNzc5ODIwNDVfMTUzNTIxMDMwMTU2Ml82YzkwNTk3MS02ZjEzLTQ4YjUtOGNhNy01YWU1ODIwN2RkYmU=

另外如果是图片大小，网络原因图片上传失败无可避免的话，像日志中图片上传失败的错误信息能否后台捕获？可以的话也算有补救措施。这问题真的很头疼，希望大神能帮我解惑，先感谢了！

**Comment by richardchien** [comment]
这个问题好像确实也有人报过，但是我复现不出来，现在不知道问题出在哪，等后面我有空再多测试测试，最近几天稍微有点忙。

你后面如果还遇到这样的问题，尝试一下把插件下载下来的 tmp 文件，改成真正的图片格式的后缀，然后 file 直接填这个文件名发送，看看能不能发出去。

b02033147 <notifications@github.com> 于 2018年8月29日周三 下午11:14写道：

**Comment by HHHHhgqcdxhg** [comment]
我也遇到了这个问题,感觉图片太大就发不出了

**Comment by richardchien** [comment]
这个问题应该和 https://github.com/richardchien/coolq-http-api/issues/141 属于同一个问题，根据 Coxxs 的判断这里应该是由于网络问题导致的
