### ISSUE TITLE
给（反向）websocket增加心跳功能

### ISSUE THREAD

**Issue by Bluefissure** [richardchien/coolq-http-api#121]
由于是API与Event分别与服务器建立websocket链接，API可以通过服务端发送心跳包保持长连接，但是Event的ws不清楚心跳要怎么实现（服务器随便发点什么东西给Event？），因此可能长时间没有Event请求的话可能断掉Event链接。
所以现在的想法是能不能设置一个定时心跳的功能，由客户端通过Event的ws发送给服务器，服务器通过API的ws返回给客户端，感觉这样可能可以减少ws链接被自动kill掉的情况。

**Comment by richardchien** [comment]
v4.5.0 测试版已经加入了心跳功能，可以去测试看看
