### ISSUE TITLE
写了一个简单的HTTP调用的PHP类

### ISSUE THREAD

**Issue by tsztodd** [richardchien/coolq-http-api#123]
https://github.com/tsztodd/coolq-richardchien

**Comment by richardchien** [comment]
emmm 你这个 repo 名字感觉，有点尴尬😂

**Comment by lietxia** [comment]
你这个在php7上不正常啊…… 
$getData = $GLOBALS['HTTP_RAW_POST_DATA']?$GLOBALS['HTTP_RAW_POST_DATA']: file_get_contents('php://input');
↓
$getData = isset($GLOBALS['HTTP_RAW_POST_DATA'])?$GLOBALS['HTTP_RAW_POST_DATA']: file_get_contents('php://input');

这种好多……折腾了半天放弃了

**Comment by kj415j45** [comment]
@lietxia 可是你为什么不把这个 comment 当成 issue 发到 [tsztodd/coolq-richardchien](https://github.com/tsztodd/coolq-richardchien)

另，安利 [kjBot](https://github.com/kj415j45/kjBot)
