### ISSUE TITLE
转发消息链接断开的问题

### ISSUE THREAD

**Issue by imlida** [richardchien/coolq-http-api#125]
转发群消息时如果包含图片和两条链接，第二条链接会断开一部分，这个问题有没有办法解决

**Comment by richardchien** [comment]
给个实例？代码和消息截图

**Comment by imlida** [comment]
![image](https://user-images.githubusercontent.com/5794390/46070354-2a20d600-c1b0-11e8-8cb2-a4e2e4ed95f8.png)
【善锦膳】手工自制牛肉酱+香辣肉酱组合装
原价36.9元【券后16.9元】包邮
领券：https://uland.taobao.com/quan/detail?sellerId=3326834620&activityId=64903bab1ba948dab5deb1174ef31e96
抢购：https://detail.tmall.com/item.htm?id=565144953139
【拍2份加送240g麻辣拌面酱】精选原料，秘制配方，粒粒大块牛肉，肉质紧密，好吃又下饭，有料才够味，开胃必备，超值必抢！
![image](https://user-images.githubusercontent.com/5794390/46070322-0fe6f800-c1b0-11e8-80d9-4bc921d05f89.png)

**Comment by imlida** [comment]
如上，有图片和两个链接时，第二个链接被截断了

**Comment by kj415j45** [comment]
![image](https://user-images.githubusercontent.com/18349191/46253922-77a38880-c4b9-11e8-9b5f-9525ae69e966.png)
囍，复现成功

**Comment by richardchien** [comment]
Coxxs 已经证实这个可能是个酷 Q bug，大概只能等待酷 Q 官方修复了

**Comment by Coxxs** [comment]
@richardchien 好可爱

**Comment by richardchien** [comment]
酷Q v5.12.3 已修复此问题
