### ISSUE TITLE
群内私聊非好友用户

### ISSUE THREAD

**Issue by leiguorui** [richardchien/coolq-http-api#126]
请问如何主动私聊群内的非好友用户?

使用send_private_msg接口报下面这个错

{
data: null,
retcode: -23,
status: "failed"
}

**Comment by richardchien** [comment]
目前酷 Q 的机制似乎是，这个用户必须最近在群里发过言，你才能私聊他

**Comment by leiguorui** [comment]
好的, 谢谢回复,
