### ISSUE TITLE
关于配置多账号的疑问，谢谢

### ISSUE THREAD

**Issue by lq200lq** [richardchien/coolq-http-api#13]
首先谢谢楼主分享此功能，另外我想问一下我看文档是允许多账号配置的，那么默认的配置会使用酷Q登陆的那个账号去发消息，多账号只配置一个QQ号的话，那是怎么登陆的？
`[general]
host=0.0.0.0
port=5700
post_url=
token=

[12345678]
post_url=http://192.168.0.11:8888
token=Mgep4rV49rM8Jf

[23456789]
port=5701`

**Comment by richardchien** [comment]
因为酷 Q 可以同时开多个，每个酷Q的进程里都会加载这个插件，但是每个进程加载插件的时候只会加载当前酷 Q 进程登录的 QQ 号的配置，所以避免冲突，最主要是端口，不同账号的端口一定要不相同

**Comment by richardchien** [comment]
如果你开了多个 QQ，但实际上只写了一个 QQ 的独立配置，那么其它的都会用默认配置

**Comment by lq200lq** [comment]
好的，明白了，多谢你的回答

**Comment by richardchien** [comment]
不客气
