### ISSUE TITLE
不支持ipv6？

### ISSUE THREAD

**Issue by njzjz** [richardchien/coolq-http-api#131]
是不是只支持ipv4？ipv4地址能正常访问，但ipv6地址无法访问。

**Comment by richardchien** [comment]
你填 `::` 就可以 
ipv6 访问了吗

**Comment by njzjz** [comment]
是的
![image](https://user-images.githubusercontent.com/9496702/47973612-5baa8c80-e0e0-11e8-8859-64b23f08878d.png)
![image](https://user-images.githubusercontent.com/9496702/47973620-6533f480-e0e0-11e8-96f5-e248e91ab994.png)
![image](https://user-images.githubusercontent.com/9496702/47973626-6bc26c00-e0e0-11e8-8804-ae4d16f2b09e.png)

**Comment by njzjz** [comment]
不过我发现设成`::`后可以兼容ipv4……

**Comment by richardchien** [comment]
😂😂

**Comment by bltsheep** [comment]
> 
> 
> 不过我发现设成`::`后可以兼容ipv4……

因为IPv6中有IPv4兼容地址，具体是::ffff:0.0.0.0/96，例如访问::ffff:114.114.114.114（或::ffff:7272:7272）和直接访问114.114.114.114的效果是一样的。监听时也是如此，例如，被IP为192.168.2.5的主机访问时，如果监听了::，来源就是::ffff:192.168.2.5。

**Comment by richardchien** [comment]
#135 

v4.6.2 开始已经默认监听 `::` 了
