### ISSUE TITLE
发送好友赞失效

### ISSUE THREAD

**Issue by liyinanCoder** [richardchien/coolq-http-api#133]
使用ws发送send_like，但是对方并没有收到好友赞
{
    "action": "send_like",
    "params": {
        "user_id":qq号,
        "times": 10
    }
}

**Comment by liyinanCoder** [comment]
日志中计入发送了名片赞，可是手Q之类的都没看看到

**Comment by richardchien** [comment]
酷Q的日志能截下图吗，另外，是用的酷Q Pro？

**Comment by liyinanCoder** [comment]
是使用的Pro  这是日志截图
![截图](https://user-images.githubusercontent.com/39552758/48592214-43f5c280-e982-11e8-9a4b-a17dbe6727b1.png)

**Comment by richardchien** [comment]
那就有点神奇了，有可能是 酷Q 的 bug，已经问了他们那边了

**Comment by Coxxs** [comment]
点赞功能目前不推荐使用，易引起封号。
