### ISSUE TITLE
尝试发送某些消息导致酷Q崩溃。

### ISSUE THREAD

**Issue by bltsheep** [richardchien/coolq-http-api#136]
![default](https://user-images.githubusercontent.com/35132976/48785848-87548600-ed20-11e8-8942-d98889ec425a.png)

插件支持发送本地图片，但是在某些情况下这个功能会导致酷Q崩溃。
运行环境：Ubuntu 18.04+Docker
酷Q与逻辑在不同机器上
引发问题的消息：
```
[CQ:image,file=file:///root/newhydrant/Bleatingsheep.NewHydrant.dll/../Konachan.com - 273820 anthropomorphism kamiyan191969 kantai_collection kisaragi_(kancolle).jpg]
```
除了上面那一条，没有其他相关日志，复现成功率100%

**Comment by richardchien** [comment]
![image](https://user-images.githubusercontent.com/5317095/49001736-914f0c80-f198-11e8-9382-e4e916a14859.png)

我现在无法复现，酷Q 会正确报错，也没有崩溃

**Comment by richardchien** [comment]
暂时先关了，如果后面发现新的线索，再打开吧
