### ISSUE TITLE
更新后语音无法发送

### ISSUE THREAD

**Issue by yearsx** [richardchien/coolq-http-api#141]
酷Q更新到最新版本后语音无法发送，[CQ:record,file=file:///d:\xxx,mp3"]；
日志显示“录音上传失败！(xxxxxxxx.tmp)”，返回错误“数据错误，无法请求发送(-11)”
插件版本4.6.1，系统Windows 2008 R2
语音组件已安装，尝试过把插件放到data/app下，还是出现同样的问题。
同样的系统环境，同样的配置，同一个语音文件，另一台机器就可能正常发送，请问大佬该如何解决啊？

**Comment by richardchien** [comment]
另一台机器的 酷Q 和插件版本也都一样吗

另外，不能发送的这台，尝试把 `.tmp` 改成 `.mp3` 看看能否播放，如果可以的话，尝试直接 `[CQ:record,file= xxxxxxxx,mp3"]` 发送这个文件，看能不能发送

**Comment by yearsx** [comment]
两台机器 酷Q和插件版本都一样；
.tmp改成.mp3可以打播放，直接发送[CQ:record,file= xxxxxxxx.mp3"]时还是失败。
![image](https://user-images.githubusercontent.com/45346318/48995658-d157c480-f183-11e8-9a79-f8c3aa2721aa.png)

**Comment by richardchien** [comment]
是不是有一台机器没有装酷Q的语音组件 https://cqp.cc/t/21132

**Comment by yearsx** [comment]
删除了，重新安装了酷Q，那台机器还是不行，一样的错误......

**Comment by richardchien** [comment]
感觉此处需要 at 叉叉 @Coxxs

**Comment by Coxxs** [comment]
@richardchien 那个不能上传的语音文件可以发一下吗

**Comment by yearsx** [comment]
@Coxxs 
[4df6e5fa8e58879e8410f6e8561ed643.zip](https://github.com/richardchien/coolq-http-api/files/2614422/4df6e5fa8e58879e8410f6e8561ed643.zip)

**Comment by Coxxs** [comment]
这里测试是正常的，可能是和消息服务器之间网络有问题。

**Comment by yearsx** [comment]
了解了，谢谢
