### ISSUE TITLE
更新后分享CQ无法发送

### ISSUE THREAD

**Issue by liyinanCoder** [richardchien/coolq-http-api#145]
![image](https://user-images.githubusercontent.com/39552758/49362589-1fd40880-f71a-11e8-9749-4db3e1cb5c29.png)
发送成功，但是没有收到

**Comment by kj415j45** [comment]
@liyinanCoder 有可能是隐形禁言，尝试发送其他消息看看？

**Comment by liyinanCoder** [comment]
@kj415j45 其他都可以，唯独分享不行

**Comment by liyinanCoder** [comment]
今天换了一个号就可以了，好像是这个账号无法发送分享。但是有时能发送有时不能发送

**Comment by liyinanCoder** [comment]
排好错了，是分享的图片原因，估计图片拉取不到，所以分享成功了也不显示

**Comment by richardchien** [comment]
OK，那先 close 了
