### ISSUE TITLE
PRO版本图片突然无法发送了

### ISSUE THREAD

**Issue by mlsjla** [richardchien/coolq-http-api#146]
[2018-12-05 16:58:56.368] [D] [HTTP] 收到 API 请求：GET /send_msg_async?message_type=group&group_id=826929629&message=%E6%96%B0%E5%B8%96%E6%8F%90%E9%86%92+%E5%8F%8D%E6%AD%A3%E6%98%AF%E4%BD%A0%E6%8F%92%E4%BB%B6%E6%9C%89%E9%97%AE%E9%A2%98%0D%0A%5BCQ%3Aimage%2Cfile%3Dhttp%3A%2F%2Fgzy.xyll.xyz%2Fdata%2Fattachment%2Fforum%2F201812%2F05%2F165844b2oo1foalj9bcqjf.png%5D%0D%0Ahttp%3A%2F%2Fgzy.xyll.xyz%2Fthread-59-1-1.html&auto_escape=0
[2018-12-05 16:58:56.368] [D] [HTTP] 开始执行动作 send_msg_async

**Comment by mlsjla** [comment]
日志一切正常，但是发送的消息没有图

**Comment by richardchien** [comment]
@mlsjla 看一下酷Q的日志

**Comment by mlsjla** [comment]
日志是空的，啥都没有。
C:\Program Files\酷Q Pro\data\log

**Comment by richardchien** [comment]
@mlsjla 酷Q的日志窗口（右击悬浮窗有个菜单项）

**Comment by mlsjla** [comment]
您好， 服务器中浏览器可以打开这个图。

**Comment by mlsjla** [comment]
我猜测是不是不支持这个网址或域名？

**Comment by liyinanCoder** [comment]
CQ分享的时候也有这个问题，有时候会因为图片导致分享没办法分享成功。

**Comment by liyinanCoder** [comment]
而日志没有任何问题，显示消息已经发送了

**Comment by richardchien** [comment]
@mlsjla 回头我试下这张图我这边能不能发
@liyinanCoder 这两个应该不是同一个问题，因为CQ分享是url直接给酷Q的，发图片是插件先下载好的

**Comment by liyinanCoder** [comment]
@richardchien 我这边所有的图片都显示上传失败。
![image](https://user-images.githubusercontent.com/39552758/49626580-89ebf680-fa15-11e8-8215-dce4b821bda6.png)

**Comment by richardchien** [comment]
@liyinanCoder 有可能类似于 #141

**Comment by liyinanCoder** [comment]
@richardchien 我重新安装了一下，还是大概率出现上传失败

**Comment by richardchien** [comment]
@liyinanCoder 你那个问题（图片上传失败）和这个 issue 的问题（文件名不合法）不是一个问题，你的是 酷Q 没能上传成功，这个是 CQHTTP 插件没能下载成功

**Comment by mlsjla** [comment]
@richardchien   那我这个问题是什么原因呢？
同样代码我服务器跑没问题的。

**Comment by richardchien** [comment]
现在你的那个图片链接失效了，可否再发一个能复现的链接来，我测试下（

**Comment by yyw258520** [comment]
这两天也遇到了，

`图片缓存下载失败，无法发送！(xxx.png)`

那个图片链接在浏览器访问又正常，ping了下图片域名gchat.qpic.cn，也是正常的。

**Comment by richardchien** [comment]
@yyw258520 感觉你这个和上面说的两个也不是同一个问题，你把链接也发来看看？我测试下

**Comment by yyw258520** [comment]
> @yyw258520 感觉你这个和上面说的两个也不是同一个问题，你把链接也发来看看？我测试下

应该是coolq的锅这两天正常了

**Comment by richardchien** [comment]
> 应该是coolq的锅这两天正常了

你的那个我觉得应该是网络环境问题，因为插件没下载成功
