### ISSUE TITLE
cooq 很容易 过期, 能否加个自动重启功能?

### ISSUE THREAD

**Issue by gitlsl** [richardchien/coolq-http-api#148]
我挂在腾讯云上,  基本就2天左右  就身份验证过期,  每次都得自己上去 重启下[其实就点一下那个快速重启],不知道插件能否加个选项, 检测到身份过期,自动重启呢

**Comment by richardchien** [comment]
@gitlsl 是不是新号，或者在不常用地点登录了，按理说不会只能登两天，目前插件的 `get_status` 方法是可以获取到在线状态的，可以自行轮训或者使用开启心跳，掉线时调用 `set_restart`

**Comment by richardchien** [comment]
这功能我考虑一下吧😂

gitlsl <notifications@github.com>于2018年12月10日 周一10:28写道：

**Comment by tengattack** [comment]
这边掉线之后是否可以增加事件上报？好像掉线之后不能收到上报的事件

**Comment by richardchien** [comment]
目前我测试的 酷Q 已经可以稳定在线一个多月了，如果过期过于频繁建议一个号在固定地点多挂一挂吧，另外由于 酷Q 现在的强制重启检测，这个功能大概不会再实现了，先 close 了。
