### ISSUE TITLE
4.6.2版本的get_status接口在Universal反向Websocket返回异常

### ISSUE THREAD

**Issue by crazywhalecc** [richardchien/coolq-http-api#149]
目前HTTP直接调用接口还是有这个问题，ws调用也是。
![image](https://user-images.githubusercontent.com/20330940/49734516-7c599980-fcbf-11e8-81c1-ce8e4af0d6e1.png)
这是调用后的CQHTTP日志
![image](https://user-images.githubusercontent.com/20330940/49734583-b2971900-fcbf-11e8-9483-4ef006450fdb.png)

**Comment by richardchien** [comment]
OK，[v4.7.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.7.0) 修复了
