### ISSUE TITLE
好像无法在docker的coolq中使用？

### ISSUE THREAD

**Issue by AsakuraFuuko** [richardchien/coolq-http-api#15]
这个 https://github.com/CoolQ/docker-wine-coolq
启用插件会报错

**Comment by richardchien** [comment]
请发一下报错的截图看看呢？我这边现在就是在这个官方 wine docker 里面用的

**Comment by AsakuraFuuko** [comment]
好像可以了 直接用那个docker镜像作为base去修改
不会报错
