### ISSUE TITLE
昨天升级了一版好像收不到加群信息了

### ISSUE THREAD

**Issue by tongv** [richardchien/coolq-http-api#150]
版本4.7.0升级之后收不到加群信息了，在【/app/io.github.richardchien.coolqhttpapi/log/111111.log】中，加群时候也看不到信息了。请问这是什么情况，没有适配官方的新接口么？

**Comment by richardchien** [comment]
看一下 酷Q 日志里面有没有相关日志

**Comment by tongv** [comment]
@richardchien 又可以了，每次升级都会闹这么一次。  楼主项目很好，一定要坚持！
