### ISSUE TITLE
自己编译生成的插件怎么运行在docker？

### ISSUE THREAD

**Issue by hundunzhidian** [richardchien/coolq-http-api#156]
通过教程构建出来的插件放在docker缺少运行库导致无法运行，大佬是怎么解决这个问题的？

**Comment by richardchien** [comment]
你用的是最新的构建脚本吗，我昨晚更新了一下，现在用 scripts/prepare.ps1 准备构建环境

如果用的是最新的构建脚本，试试构建 release 版

huang <notifications@github.com>于2019年1月11日 周五10:04写道：

**Comment by hundunzhidian** [comment]
恩，刚刚使用了构建脚本测试了下，可以运行在docker了，谢谢
