### ISSUE TITLE
建议上报接口添加回调功能

### ISSUE THREAD

**Issue by 1294822** [richardchien/coolq-http-api#16]
由于目前没有回调功能，coolq会把数据再交给其他插件处理。我看代码也预留的回调接口，能不能实现下啊。或者加个参数阻止下其他插件也行啊。
ps：项目相当棒，赞一个。

**Comment by richardchien** [comment]
啊，你这么一说，我竟然忘记这个问题，还有拦截消息的需求。你说得对，下个版本会加上！谢谢你的建议！

**Comment by 1294822** [comment]
神，等你哦…最好是实现回调啊，这样就不用再发起一个http请求了。

**Comment by richardchien** [comment]
v1.1.0 开始支持了～见 https://github.com/richardchien/coolq-http-api/releases/tag/v1.1.0
