### ISSUE TITLE
日志窗口黑屏

### ISSUE THREAD

**Issue by 502647092** [richardchien/coolq-http-api#160]
![image](https://user-images.githubusercontent.com/10203793/52065550-b8b7c080-25b1-11e9-8cc7-585f3fb2abb1.png)

**Comment by zzm88** [comment]
我也是这样

**Comment by Ice-Cirno** [comment]
这个截图中似乎只是个控制台，右键悬浮窗再打开日志即可

**Comment by richardchien** [comment]
我发现 docker 里面有可能是 wine 把容器的标准输出作为这个控制台了，用 `docker logs` 应该可以看到这个日志
