### ISSUE TITLE
在docker环境下使用20分钟左右之后无法正常发送消息

### ISSUE THREAD

**Issue by JAstray** [richardchien/coolq-http-api#161]
环境：
docker 1.13.1
    image-dorowu/ubuntu-desktop-lxde-vnc
wine 3.0    指定32位环境
winetricks
    msscript
    winhttp
coolQ-Pro-5.12 小i版
    语音组件
 
SDK：
richardchien/nonebot 

根据日志已经查明酷q的收发和SDK的收发没有问题
http-api模块的消息通知也没有问题
但是消息的发送无论是http还是ws都无效

**Comment by richardchien** [comment]
贴一下你 CQHTTP 插件的配置文件呢？

**Comment by JAstray** [comment]
> 贴一下你 CQHTTP 插件的配置文件呢？

{
    "host": "[::]",
    "port": 5700,
    "use_http": true,
    "ws_host": "[::]",
    "ws_port": 6700,
    "use_ws": false,
    "ws_reverse_url": "",
    "ws_reverse_api_url": "ws://47.101.62.246:8080/ws/api/",      # 47.101.62.246为服务器的公网IP
    "ws_reverse_event_url": "ws://47.101.62.246:8080/ws/event/",
    "ws_reverse_reconnect_interval": 3000,
    "ws_reverse_reconnect_on_code_1000": true,
    "use_ws_reverse": true,
    "post_url": "",
    "access_token": "",
    "secret": "",
    "post_message_format": "string",
    "serve_data_files": true,
    "update_source": "github",
    "update_channel": "stable",
    "auto_check_update": false,
    "auto_perform_update": false,
    "show_log_console": false,
    "log_level": "debug"
}

docker端口映射 5700:5700 6700:6700
nonebot服务位于宿主机 run(0.0.0.0, 8080)

**Comment by JAstray** [comment]
在排查的过程中将下面几项
"ws_reverse_api_url": "ws://{server_ip}:{port}/ws/api/", 
"ws_reverse_event_url": "ws://{server_ip}:{port}/ws/event/",
"log_level": "Info"
修改为
"ws_reverse_api_url": "ws://172.17.0.1:8080/ws/api/",
"ws_reverse_event_url": "ws://172.17.0.1:8080/ws/event/",
"log_level": "Debug"
之后，到现在为止暂时没有再出现无法正常发送消息的情况。

之前使用的宿主机的外网IP连接nonebot也是能连接上的，只是二十分钟后无法对请求做出响应。但是为什么会出现这样的区别还是不得解。
如果大佬知晓，希望能指点一番。
谢谢！

**Comment by richardchien** [comment]
@JAstray 应该是你的 VPS 提供商隐式掐了连接，之前有人也报过类似的问题

**Comment by JAstray** [comment]
感谢解答！
