### ISSUE TITLE
获取群成员被禁言状态及剩余禁言时间

### ISSUE THREAD

**Issue by Raka-loah** [richardchien/coolq-http-api#163]
机器人通过API的禁言操作会覆盖已有禁言状态的时间，导致机器人群管操作可能使其他管理员的手工禁言时长发生变化。目前/get_group_member_info并没有禁言状态相关字段，是否有其它方式可以获取到相关数据？

**Comment by richardchien** [comment]
@Raka-loah 酷Q没有提供这个接口，所以做不到‘

**Comment by Raka-loah** [comment]
感谢回复！
