### ISSUE TITLE
给好友发送带回车的消息怎么处理?

### ISSUE THREAD

**Issue by yuhuan21** [richardchien/coolq-http-api#166]
调用send_private_msg给好友发送消息,如果是一行打完的文字,发送是正常的
1.但是消息一旦有换行,发送就会失败,而且接口也不会返回任何消息,只返回一个空值,这个应该怎么处理?
2.顺便问一下如果有一些特殊符号之类的又如何处理?
谢谢大神!
![image](https://user-images.githubusercontent.com/10203925/53295587-a2f88c80-3839-11e9-8f98-64ca814b2fbe.png)

**Comment by kj415j45** [comment]
@yuhuan21 urlencode() 了解一下

**Comment by yuhuan21** [comment]
@kj415j45 试过了,QQ收到的信息就变成了"%e4%bd%a0%e5%a5%bd"这种编码

**Comment by richardchien** [comment]
使用 POST 请求，请求体使用 JSON 格式，不要用 urlencoed form

**Comment by yuhuan21** [comment]
@richardchien 我用得就是JSON数据,但是不知道这些回车双引号之类的应该转义成什么符号了,

**Comment by richardchien** [comment]
@yuhuan21 请多多搜索 JSON 相关知识
