### ISSUE TITLE
用Mac docker coolQ配置

### ISSUE THREAD

**Issue by chilampoon** [richardchien/coolq-http-api#167]
如果是用macos, `ws_reverse_api_url` & `ws_reverse_event_url`里面的地址应该是填本机ip而非[文档](https://none.rclab.tk/guide/getting-started.html)中的 `172.17.0.1`.

我查到的:

>  official recommendation is to connect to the special DNS name `host.docker.internal`, which resolves to the internal IP address used by the host

我用 `172.17.0.1` 之类的试了好多次都不行，然后查了下改了本机ip才行，搞得本小白迷茫了两天QAQ

Reference:
https://stackoverflow.com/questions/38504890/docker-for-mac-1-12-0-how-to-connect-to-host-from-container

**Comment by richardchien** [comment]
macOS 上好像比较特殊，我以前是通过 ifconfig alias 解决的

Darklings <notifications@github.com>于2019年2月24日 周日21:54写道：

**Comment by crazywhalecc** [comment]
```echo "show State:/Network/Global/IPv4" | scutil | grep PrimaryInterface | awk '{print $3}' | xargs ifconfig | grep inet | grep -v inet6 | awk '{print $2}'```
can solve this.

**Comment by TPIOS** [comment]
遇到了同样的问题，通过ifconfig查看公网ip，然后**改成**公网ip即可，研究了2个多小时
