### ISSUE TITLE
为什么没有接受消息的API

### ISSUE THREAD

**Issue by yanyuxuanz** [richardchien/coolq-http-api#170]
大哥你好！在我根据你提供的golang框架里，不管长轮询，还是websocket,不是超时就是失败，在我分析完他的代码后发现，都是调用get_updates这个API.当我回来找的时候。发现根本没有获取消息的API，哪里去啦？

**Comment by SettingDust** [comment]
@yanyuxuanz Close了呗这个 @richardchien

**Comment by richardchien** [comment]
请注意阅读那个 SDK 的 [README](https://github.com/catsworld/qq-bot-api#communication-methods)，使用长轮询方式是需要额外安装扩展的

**Comment by rikakomoe** [comment]
> 不是超时就是失败

是我那边的锅，https://github.com/catsworld/qq-bot-api/issues/13 ，已经修复了，更新一下再试试吧
