### ISSUE TITLE
无法连接软件更新服务器

### ISSUE THREAD

**Issue by xjr100419** [richardchien/coolq-http-api#172]
docker run -d -ti --rm --name cqhttp-test  -v $(pwd)/coolq:/home/user/coolq  -p 9000:9000  -p 5700:5700  -e COOLQ_ACCOUNT=123456  -e CQHTTP_POST_URL=http://example.com:8080  -e CQHTTP_SERVE_DATA_FILES=yes  richardchien/cqhttp:latest

**Comment by xjr100419** [comment]
![TIM截图20190402172912](https://user-images.githubusercontent.com/8691355/55392022-0d08fd80-556d-11e9-9b03-5cf927713343.png)

**Comment by xjr100419** [comment]
换个服务器就可以了。。
不过 两个服务器都是 可以连外网的。。
酷Q Air 具体是 要连接那个地址的么？

**Comment by richardchien** [comment]
这个属于 酷Q 的问题，应该是你服务器到了 酷Q 更新服务器不太通畅

xjr100419 <notifications@github.com>于2019年4月3日 周三10:01写道：
