### ISSUE TITLE
请问，移除set_restart接口是基于什么原因呢？

### ISSUE THREAD

**Issue by aond** [richardchien/coolq-http-api#176]

**Comment by Coxxs** [comment]
酷Q 被设计为可以长期稳定运行，通过**结束进程的方式强制重启**可能会使软件数据、应用数据损坏，造成数据损失以及运行异常。
新版 酷Q 中增加了异常退出的检测，为避免强制重启功能进一步被误用，cqhttp 移除了该接口。

**Comment by aond** [comment]
如果，酷Q上登陆的QQ号，异常退出(比如：其他移动端登录了该QQ), 之前可以通过 set_restart 接口重启，已实现重新登录。
但现在处理这种情况就只能，手动处理重新登录。是否可以考虑以下优化这种情况的处理。

ps: 现在 /get_status 获取插件运行状态 接口也不存在了，是移除了吗？

**Comment by richardchien** [comment]
@aond get_status 应该还是在的，没动过。

你这个场景看起来确实有道理，不过现在 酷Q 确实在非正常重启后会有 60 秒的倒计时。也许这个功能确实需要重新考虑。

**Comment by richardchien** [comment]
`get_status` 接口在 酷Q 最近一次更新后确实出现了不兼容，具体讨论见 #177 ，修复已经完成，大概今晚发版本

**Comment by richardchien** [comment]
由于 v4.9.0 移除 `set_restart` 后影响较大，v4.10.0 重新加入了此接口，但已标注为试验性接口，接口名修改为 `_set_status`，请大家注意修改代码中相应的调用。

v4.10.0 也修复了 `get_status` 接口的 bug。

**Comment by aond** [comment]
在4.10.1中调用无法调用`_set_restart` 但还是可以调用 `set_restart`, 但是存在以下问题：
调用`set_restart`返回成功后，coolq客户端并未重新启动并重新登录QQ，而是客户端报错，提示 

> 应用模块意外退出，可能是某个应用程序试图强制关闭或重启酷Q

> 您已登陆账号，****， 不能重复登录

按照我的理解，既然我调用了重启coolq的接口(说明我已经明确地知道需要对客户端进行重启)，返回了正确的数据，那么客户端就不应该报第一个错误；还有既然是重启，那么自然我现在并不关心QQ是否在线(有时在线检测结果并不准确)，所以第二个报错也不应出现(是否可以在重启时先退出登录).

**Comment by richardchien** [comment]
@aond 你可能用的不是真的 4.10.1😂，那个报错是 酷Q 报的，不是插件，之前旧版的重启 酷Q 功能不兼容最新的 酷Q。最好再检查一下插件版本

**Comment by aond** [comment]
![image](https://user-images.githubusercontent.com/48431543/59586071-9663b100-9114-11e9-9962-baea6857fb4e.png)
可以确定是 4.10.1

**Comment by richardchien** [comment]
@aond 去 VNC 里面右击 酷Q 悬浮窗 - 应用管理 里面看
