### ISSUE TITLE
get_status 方法无法正常工作（无任何返回）

### ISSUE THREAD

**Issue by Akyuu** [richardchien/coolq-http-api#177]
在Debian9下通过Docker的方式部署了[richardchien/cqhttp](https://hub.docker.com/r/richardchien/cqhttp/)，并且通过VNC完成了登录，插件版本为4.9.0

但是在部署完成后使用`curl`命令测试时，发现`get_status`方法无法正常工作，其他方法正常。

具体命令：

```
~ # curl -H 'Authorization: Token 123456' http://cqhttp:5700/get_login_info

{"data":{"nickname":"123","user_id":123456},"retcode":0,"status":"ok"}



~ # curl -H 'Authorization: Token 123456' http://cqhttp:5700/get_status

curl: (52) Empty reply from server
```

此时进入容器查看`/home/user/coolq/app/io.github.richardchien.coolqhttpapi`目录下的日志文件，发现只有

```
[2019-04-11 09:45:46.437] [I] [HTTP] 已成功处理一个 API 请求：/get_login_info
```

没有调用`get_status`方法的日志

**Comment by richardchien** [comment]
@Akyuu 还没有详细查看，目前猜测是因为 酷Q 日志数据库改名导致 CQHTTP 读取失败抛了异常，可以尝试把配置的 online_status_detection_method 改成 get_stranger_info

**Comment by Akyuu** [comment]
> @Akyuu 还没有详细查看，目前猜测是因为 酷Q 日志数据库改名导致 CQHTTP 读取失败抛了异常，可以尝试把配置的 online_status_detection_method 改成 get_stranger_info

有效，检测方式改为 get_stranger_info 之后， `get_status` 方法可以正常工作。

另外测试了一下，不修改检测方式，而是创建一个名为 logv1.db 的软链接指向新的日志文件 logv2_201904.db 也可以让 `get_status` 方法正常工作，基本可以确定是由于日志数据库改名引起的错误。

**Comment by richardchien** [comment]
v4.10.0 修复了
