### ISSUE TITLE
post_url无法访问

### ISSUE THREAD

**Issue by 10142904** [richardchien/coolq-http-api#180]
碰到一个奇怪的问题，我的一台win10机器装的coolq-http-api(4.9和4.10都试过了)始终无法上报事件，报“上报地址无法访问”，但我用浏览器测试了是可以访问的。更奇怪的是另外一台win10机器同样版本的coolq-http-api，同样的post_url，就没问题，正式怎么回事。
我的酷Q的版本是5.13.5（190414）
coolq-http-api版本是4.9

**Comment by richardchien** [comment]
@10142904 应该是设置了系统全局代理

**Comment by 10142904** [comment]
多谢大大回复，但我这个机器目前没有开代理，用IE访问这个post_url没问题，用wireshark抓包也没看到coolq-http-api发起的tcp连接，还可能是什么原因呀

**Comment by 10142904** [comment]
找到原因了，是系统环境变量中设置了all_proxy变量的原因，多谢@richardchien指点！
