### ISSUE TITLE
CQ码[image]引用网络图片的后缀tmp能不能换成jpg或者png

### ISSUE THREAD

**Issue by piikee** [richardchien/coolq-http-api#181]
CQ码[image]引用网络图片的后缀tmp能不能换成jpg或者png。
tmp后缀发出去容易被Q群屏蔽了，能不能根据网络图片判断后缀然后使用网络图片的后缀或者直接png后缀，不要用tmp后缀。。。

**Comment by richardchien** [comment]
v4.10.1 已经更新
