### ISSUE TITLE
【Bug】获取群成员列表接口 /get_group_member_list

### ISSUE THREAD

**Issue by RheaBubbles** [richardchien/coolq-http-api#186]
获取群成员列表接口 `/get_group_member_list`在3000人群中无法获取到实际的群成员列表，只能获取到部分人的信息，有时候只有几个人，而且重复请求都是返回那几个人的信息，没有返回错误码。

```
{
  data: [ ... ],
  retcode: 0,
  status: 'ok'
}
```

个人猜测是大量人数的群成员列表获取需要一点时间？
不知道是不是超过了什么时间限制导致了错误数据。

酷Q版本是Air
运行环境Windows10 64位

**Comment by RheaBubbles** [comment]
隔了一段时间又测试了一下，会有一次299人信息的获取，然后之后再重复获取只能获取到5个人的信息，应该是酷Q获取列表需要一点时间，建议在这部分添加一个异步接口版本，在大人数群中才能获取到完整的成员信息。

**Comment by winwill2012** [comment]
我也遇到了，兄台怎么解决的？

**Comment by RheaBubbles** [comment]
> 我也遇到了，兄台怎么解决的？

估计在两个地方可能有问题：

- HTTP API插件
- API插件使用的酷Q C++ SDK

但是鉴于懒得去看代码查证了，目前猜测至少有一个地方在大群的人员列表获取有同步请求的Bug。

因为我是只面向一个大群做开发，所以干脆直接用了一个数据库来维护成员列表了，他们应该还要等一段时间才能修复这个。

**Comment by winwill2012** [comment]
我的一个很小的群（3个人），获取群成员列表也会有问题的，跟群大小应该没关系。

**Comment by Coxxs** [comment]
新版已修复，重启软件即可。

**Comment by Coxxs** [comment]
如果还不行的话，可能需要删除 data/[Account]/cache.db 的缓存

**Comment by winwill2012** [comment]
我重启了docker，并且删除了cache.db，但是获取群成员列表还是有问题

**Comment by richardchien** [comment]
@winwill2012 有提示更新了酷Q吗

**Comment by winwill2012** [comment]
怎么更新？我pull了最新的docker image，然后删除data下的cache.db，然后重启服务。
调用获取群成员列表的接口还是有问题

**Comment by richardchien** [comment]
@winwill2012 你看下酷Q版本是不是 5.14.4

**Comment by winwill2012** [comment]
5.14.3A（190505）

**Comment by richardchien** [comment]
有可能酷Q还没推送到，尝试在其他地方更新之后把自己 CQA.exe 或者 CQP.exe 替换过去看看

qifuguang <notifications@github.com>于2019年5月9日 周四19:20写道：

**Comment by winwill2012** [comment]
更换CQA会启动时会报错
![image](https://user-images.githubusercontent.com/9719716/57459057-104a8400-72a5-11e9-858d-9a767cd2b03c.png)

**Comment by richardchien** [comment]
可能需要同时覆盖 `.exe` 与 `bin` 目录。这个网络问题大概需要去 酷Q 的 [问题反馈 · 跟踪](https://cqp.cc/b/issue) 板块问了（请阅读其发帖规则）。

**Comment by winwill2012** [comment]
我看了一下，现在已经好了，感谢！
