### ISSUE TITLE
sand_like  显示是ok，但是实际好友的赞并没有增加

### ISSUE THREAD

**Issue by zongqiqi** [richardchien/coolq-http-api#189]
如题

**Comment by zongqiqi** [comment]
添加 time参数，请求就失败了

**Comment by richardchien** [comment]
这是 酷Q 的 bug，可以去 酷Q 论坛反馈

实际上 酷Q 已经不建议用这个接口了，不稳定并且容易被封号

**Comment by richardchien** [comment]
并且，不要发重复 issue，https://github.com/richardchien/coolq-http-api/issues/188 和 https://github.com/richardchien/coolq-http-api/issues/133 都是同样的主题，建议先搜索有没有相似 issue 再发
