### ISSUE TITLE
对加友加群的请求处理有很大概率报错（-21 临时消息已失效或未建立）

### ISSUE THREAD

**Issue by qiaohs** [richardchien/coolq-http-api#19]
不懂出错的原因呢，感觉可能是在传输过程中flag因为编码问题出错，因为添加请求手动可以处理，而且试了下flag写错也会报-21

> 收到 HTTP 请求，请求方式：GET，URI：/set_friend_add_request?flag=AAAAAIwqlJgAAAAAAAAAAAADSAoKhn1AWN+cjQ==&approve=true
> 找到 handler：set_friend_add_request
> 错误：临时消息已失效或未建立(-21)
> 响应内容发送完毕

**Comment by qiaohs** [comment]
又试了几次，感觉是间歇性的，一段时间内怎么处理都会出错，重启coolQ也没效果。
看了下flag内容，只有小部分小写字母是变化的，突然感觉编码问题的可能性很小，作为小白实在想不通qwq，不知道大大遇到过这种情况没。coolQ今天刚升级的最新版

**Comment by richardchien** [comment]
唔……其实，我日常用的时候，并没有用到处理请求的功能，所以其实这部分由于我代码的问题出 bug 的可能性也是有的。我现在在写另外一个功能，明天再来测试一下你这个问题吧，抱歉啦

**Comment by qiaohs** [comment]
soga，谢谢回复~加油~~

**Comment by richardchien** [comment]
我刚刚测了几次，没有复现，会不会是因为你请求的时候 flag 的内容没有 urlencode？

**Comment by richardchien** [comment]
那个 base64 里面可能有些符号会被误解（等号啥的），所以我代码里面收到请求会先 urldecode

**Comment by qiaohs** [comment]
嗯嗯是这样的，我竟然一直没想到。。上面那段里面有了+号，好大意qwq辛苦了~

**Comment by richardchien** [comment]
另外，新版本可以直接在上报请求的响应里面同意或拒绝请求了，也就不用再发 flag 了，可以试试看

**Comment by qiaohs** [comment]
好啊好啊~

**Comment by allovine** [comment]
之前用的好好的，前两天忽然开始报错，临时消息已失效或未建立

**Comment by ExerciseBook** [comment]
@allovine 刚刚在醋Q群没讲完顺便说清楚一点吧。

遇到这种情况可能是缓存炸了。删 data/QQ号 文件夹重建缓存即可解决。

尽可能避免kill酷Q进程吧。

**Comment by allovine** [comment]
谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Eric_Lian <notifications@github.com>
发送时间: 2020年1月6日 13:54
收件人: richardchien/coolq-http-api <coolq-http-api@noreply.github.com>
抄送: allovine <liyaofeng@52jiaoshi.com>, Mention <mention@noreply.github.com>
主题: 回复：[richardchien/coolq-http-api] 对加友加群的请求处理有很大概率报错（-21 临时消息已失效或未建立） (#19)




@allovine 刚刚在醋Q群没讲完顺便说清楚一点吧。
 
遇到这种情况可能是缓存炸了。删 data/QQ号 文件夹重建缓存即可解决。
 
尽可能避免kill酷Q进程吧。
