### ISSUE TITLE
获取群成员信息，群消息上报等，可不可以返回头像url这个字段

### ISSUE THREAD

**Issue by hupengcool** [richardchien/coolq-http-api#190]
获取群成员信息，群消息上报等，可不可以返回头像url这个字段

**Comment by hupengcool** [comment]
还有群头像等

**Comment by richardchien** [comment]
这个已经解决了吗？头像可以直接通过 QQ 号拼出来，比如：

```
https://q.qlogo.cn/headimg_dl?bs=qq&dst_uin={qq}&spec=0
https://q.qlogo.cn/headimg_dl?bs=qq&dst_uin={qq}&spec=40
https://q.qlogo.cn/headimg_dl?bs=qq&dst_uin={qq}&spec=140
https://q.qlogo.cn/headimg_dl?bs=qq&dst_uin={qq}&spec=640
```

`{qq}` 需要换成 QQ 号

**Comment by ExerciseBook** [comment]
具体接口使用http调试工具查一下QQ客户端的运作模式就好。

**Comment by hupengcool** [comment]
> 这个已经解决了吗？头像可以直接通过 QQ 号拼出来，比如：
> 
> ```
> https://q.qlogo.cn/headimg_dl?bs=qq&dst_uin={qq}&spec=0
> https://q.qlogo.cn/headimg_dl?bs=qq&dst_uin={qq}&spec=40
> https://q.qlogo.cn/headimg_dl?bs=qq&dst_uin={qq}&spec=140
> https://q.qlogo.cn/headimg_dl?bs=qq&dst_uin={qq}&spec=640
> ```
> 
> `{qq}` 需要换成 QQ 号

问题已经解决了,我是通过下面的url来的
QQ头像url：https://q4.qlogo.cn/g?b=qq&nk=qq&s=140
QQ群头像url：https://p.qlogo.cn/gh/{groupNo}/{groupNo}/140
另外 @richardchien 在上报群消息的时候，上报群号的同时，能否带上一个群名称。thanks

**Comment by ExerciseBook** [comment]
@hupengcool 可以自己取群名。。。
先取群列表，再遍历一波群列表。

**Comment by hupengcool** [comment]
> @hupengcool 可以自己取群名。。。
> 先取群列表，再遍历一波群列表。
我现在是这么做的，只是有点不方便，这个群列表我是获取之后，缓存，设了个过期时间。每次取也麻烦。如果上报的时候能直接提供会方便很多 @ExerciseBook

**Comment by ExerciseBook** [comment]
@hupengcool 那没啥问题（
看看rc愿不愿意写吧。反正无论是谁写都是这样写的（

**Comment by hupengcool** [comment]
@ExerciseBook 嗯，我只是提个建议~，作为使用者而言，当然是想越省事越好了。

**Comment by richardchien** [comment]
这个暂时不行，因为 酷Q 那边这个是分开的接口，我最近也没空更新

hupeng <notifications@github.com>于2019年5月31日 周五11:48写道：
