### ISSUE TITLE
【/set_group_kick 群组踢人】接口是否能增加踢出失败的响应

### ISSUE THREAD

**Issue by Ice-Hazymoon** [richardchien/coolq-http-api#193]
如题，如果没有管理员权限或者没有这个群员的话，是否能返回移除失败的相关信息

或者增加一个获取当前bot是否是群管理的接口？酷Q是否能实现

**Comment by richardchien** [comment]
@Ice-Hazymoon 你可以通过 get_group_member_info 获取到机器人在群聊中的信息，在 role 字段

**Comment by ExerciseBook** [comment]
@Ice-Hazymoon 可以考虑在踢完之后取群员信息看看这个人是否存在。

**Comment by Ice-Hazymoon** [comment]
感谢回复，已经解决
