### ISSUE TITLE
修改:酷Q无法获取到 安卓手机端 文字加图片的 图片url

### ISSUE THREAD

**Issue by wangdakanga** [richardchien/coolq-http-api#202]
当手机发送文字加图片信息给cool cqimg里的url为空,所以导致了coolhttp获取不到图片
### 操作步骤
 1. 打开聊天窗口
 2. 选择一张图片
 3. 输入文字,然后点击文字输入框右侧的发送(不是图片的发送)

### 酷Q 版本
**酷Q Air 5.14.8A(190518)**

### qq版本
安卓 V8.0.5.4040

### cqimg文件
```
[image]
md5=[*****手动打码*****]
width=1080
height=2340
size=203083
url=
addtime=1560411616
[notice]
致开发者=由于消息服务器的更新，本文件中的 url 已被弃用，并将在未来被移除，请勿直接读取本文件。请更新至最新版 SDK，并使用 Api（CQ_getImage, 接收图片）读取本图片。

```

**Comment by Coxxs** [comment]
感谢详细反馈，酷Q是运行在哪里的？如果是云服务器的话，能否提供一下地域和可用区便于测试。

**Comment by wangdakanga** [comment]
> 感谢详细反馈，酷Q是运行在哪里的？如果是云服务器的话，能否提供一下地域和可用区便于测试。
哎..我本地运行的酷Q 位置是在 安徽合肥 电信
我使用python nonebot调用coolq-http-api,查了代码 我猜测是 coolq-http-api 直接读取cqmsg url配置 导致的问题 所以应该不是酷Q的问题

**Comment by richardchien** [comment]
表现出来 cqhttp 有什么反应吗，是报错还是只是 CQ 码里面没有 `url` 字段

**Comment by wangdakanga** [comment]
> 表现出来 cqhttp 有什么反应吗，是报错还是只是 CQ 码里面没有 `url` 字段

cq码里没有url字段

内容是
```
[CQ:image,file=D700037C620CD08083F91B68D37FA1D0.jpg]
```

使用 HTTP /get_image?file=D700037C620CD08083F91B68D37FA1D0.jpg 返回
```
{
    "data": null,
    "retcode": 102,
    "status": "failed"
}
```

表现的结果为在 nonebot 中 session.current_arg_images = []
![fail](https://user-images.githubusercontent.com/8704036/59447000-249a1780-8e35-11e9-93eb-ef0e67b02a87.png)
如果我单独发送图片是可以的
![success](https://user-images.githubusercontent.com/8704036/59447065-4398a980-8e35-11e9-9101-75eddc067abd.png)

因为我查看cqimg看到提示 并且没有在cqhttp的代码中找到`CQ_getImage`的调用,所以我猜测是没有使用最新API导致的

第一次单独发送图片可以成功获取url  第二次 发送"#记账 [图片]" current_arg_images = [] 中没有url 使用 /get_image? 也无法获取到图片 
![qq_pic_merged_1560440623690](https://user-images.githubusercontent.com/8704036/59447421-c6216900-8e35-11e9-9e93-404cc6f7ede2.jpg)

**Comment by richardchien** [comment]
> 因为我查看cqimg看到提示 并且没有在cqhttp的代码中找到`CQ_getImage`的调用,所以我猜测是没有使用最新API导致的

你调用的 `/get_image` 接口实际上就是调用的 `CQ_getImage`，从返回错误码 102 来看，是 酷Q 由于某种原因没有得到那个 URL，这种情况下插件上报的 CQ 码里面没有 `url` 字段也是符合预期的，应该要等 酷Q 修复

**Comment by wangdakanga** [comment]
> > 因为我查看cqimg看到提示 并且没有在cqhttp的代码中找到`CQ_getImage`的调用,所以我猜测是没有使用最新API导致的
> 
> 你调用的 `/get_image` 接口实际上就是调用的 `CQ_getImage`，从返回错误码 102 来看，是 酷Q 由于某种原因没有得到那个 URL，这种情况下插件上报的 CQ 码里面没有 `url` 字段也是符合预期的，应该要等 酷Q 修复

好的 谢谢您

**Comment by richardchien** [comment]
这个问题似乎已经过了很久，先关了，如果确实还有这个问题的话可以重新打开讨论
