### ISSUE TITLE
[SDK]node-coolq-robot，基于cq-robot、coolq-http-api、cq-websocket ，按照官方SDK风格重新封装了事件函数和api函数

### ISSUE THREAD

**Issue by CaoMeiYouRen** [richardchien/coolq-http-api#203]
1.仿官方SDK风格，熟悉易语言版的很快就可以上手。

2.仿酷Q目录设计，可以像原生酷Q插件那样载入插件，也便于插件的开发

3.可以使用JavaScript和TypeScript进行开发，具有一定的跨平台性

4.对于所有异步函数均采用async/await重新封装函数，使调用api更加方便。

5.提供下划线和驼峰式两种api函数风格，使函数调用更加方便

**Comment by richardchien** [comment]
你的链接呢😂，可以直接照着之前的格式直接修改 README 发 PR 吧

**Comment by CaoMeiYouRen** [comment]
> 你的链接呢😂，可以直接照着之前的格式直接修改 README 发 PR 吧
不好意思一时忘记了。。。

**Comment by CaoMeiYouRen** [comment]
https://github.com/CaoMeiYouRen/node-coolq-robot

**Comment by richardchien** [comment]
已合并为 PR
