### ISSUE TITLE
在docker下，发送稍大的gif提示“数据错误，无法请求发送”

### ISSUE THREAD

**Issue by VSakuya** [richardchien/coolq-http-api#206]
使用框架：nonebot
酷q pro版本最新
http api版本最新
在windows下使用相同代码发送不会产生该问题，但是在docker下发送就不行，我是发送本机就存在的图片。下图是酷Q提示的错误
![2019-07-23_174607](https://user-images.githubusercontent.com/10345763/61702278-1adbcc00-ad72-11e9-95f9-9c8464f04ce9.png)
下面的是我尝试发送的gif
[1563874945933.zip](https://github.com/richardchien/coolq-http-api/files/3421381/1563874945933.zip)
补充，使用相同代码发送较小gif并不会产生相同问题。

**Comment by ExerciseBook** [comment]
这个貌似是醋Q的问题。

**Comment by VSakuya** [comment]
> 
> 
> 这个貌似是醋Q的问题。

但是windows下不会有相同问题，我已经提到了

**Comment by ExerciseBook** [comment]
但是这真的就是酷Q的锅。

**Comment by richardchien** [comment]
大 GIF 好像确实会有问题，你检查一下两个环境下 cqhttp 下载的 GIF 是不是完全一样的，如果是一样，那就是 酷Q 对 Wine 的兼容问题

**Comment by VSakuya** [comment]
> 
> 
> 大 GIF 好像确实会有问题，你检查一下两个环境下 cqhttp 下载的 GIF 是不是完全一样的，如果是一样，那就是 酷Q 对 Wine 的兼容问题

是完全一样的，这一张gif的问题我已经处理了几个星期了，所以文件源始终没变。

**Comment by ExerciseBook** [comment]
@VSakuya 实际上这个问题在windows上也有发生。。。而且最近我也见到不少反馈了。

**Comment by VSakuya** [comment]
> 
> 
> @VSakuya 实际上这个问题在windows上也有发生。。。而且最近我也见到不少反馈了。

我在windows上复现了几次都没有成功，我是win10最新系统。

**Comment by richardchien** [comment]
> 是完全一样的，这一张gif的问题我已经处理了几个星期了，所以文件源始终没变。

那就是 酷Q 的问题了，我记得机器人群里的那个 SB bot 的倒放 GIF 就是超过一定大小就发不了的。

先 close 了，可以去 酷Q 论坛看看有没有相关 issue。
