### ISSUE TITLE
_get_friend_list返回104

### ISSUE THREAD

**Issue by scriptwang** [richardchien/coolq-http-api#207]
文档写的104代表获取cookie凭证失败，需要刷新缓存，但日志显示获取cookie成功，返回内容如下
```
{
    "data": null,
    "retcode": 104,
    "status": "failed"
}
```
![image](https://user-images.githubusercontent.com/19930877/61988411-6f719680-b053-11e9-97ec-a68692a4940a.png)
在全新环境下运行http api，还是一样的104，应该排除缓存问题。

**Comment by ExerciseBook** [comment]
目测是QQ换接口了吧 🤔

**Comment by scriptwang** [comment]
> 目测是QQ换接口了吧 🤔

我也是这种赶脚。。。。

**Comment by richardchien** [comment]
@scriptwang 这个接口已经凉了，目前只能自己去找其他能用的接口了

**Comment by scriptwang** [comment]
> @scriptwang 这个接口已经凉了，目前只能自己去找其他能用的接口了

哦哦哦哦哦，
