### ISSUE TITLE
运行在windowsServer2012R2上 总是报错 retcode104 

### ISSUE THREAD

**Issue by JavaZhangYin** [richardchien/coolq-http-api#209]
在本地win10运行没有问题一切正常
移到 windowsServer2012R2上 发送请求相应时间很长，我用的127.0.0.1访问的 不会有ip错误的问题 总是报错 retcode104  但是本地没有这个问题 请问如何解决

**Comment by richardchien** [comment]
@JavaZhangYin 104 是 酷Q 返回数据异常，清理一下 酷Q 缓存重新登录试试

**Comment by JavaZhangYin** [comment]
> @JavaZhangYin 104 是 酷Q 返回数据异常，清理一下 酷Q 缓存重新登录试试
还是不行 重新解压了 酷Q 重新安装插件 调用同一个方法 还是出现之前的问题 
我唯一的变量就是环境 其他的没有改动 所以我想请问 windowsserver 运行 酷Q 或者 这个插件 需要额外配置什么东西吗？

**Comment by richardchien** [comment]
@JavaZhangYin 那应该是网络问题，你能拿到这个错误，说明插件运行着了

**Comment by JavaZhangYin** [comment]
> @JavaZhangYin 那应该是网络问题，你能拿到这个错误，说明插件运行着了

我感觉不是插件的问题 是 酷Q的问题 其他的插件有的也不能正常运行
