### ISSUE TITLE
发现一个接口问题

### ISSUE THREAD

**Issue by Karensen** [richardchien/coolq-http-api#21]
就是加群或者邀请加群的时候没有群号的接口啊？

**Comment by richardchien** [comment]
我还真给忘了……稍等，马上加

**Comment by Karensen** [comment]
是事件上报里边没有，大佬幸苦了，可惜俺只会点php，c++以后再慢慢琢磨，目前还搞不定，只能麻烦大佬写接口

**Comment by richardchien** [comment]
我其实也是边摸索编写，现在的这个代码写的有点乱了，后面想找机会重构一下，得等有空才行。

bug 解决了，https://github.com/richardchien/coolq-http-api/releases/tag/v1.1.2
