### ISSUE TITLE
docker中日志窗口黑屏

### ISSUE THREAD

**Issue by zzm88** [richardchien/coolq-http-api#211]
环境：阿里云Ubuntu 下的docker
翻看log发现是有信息的，但是弹出的日志框中只有黑屏

**Comment by richardchien** [comment]
是这样的，这是个已知问题，因为 Wine 的兼容性问题

zzm88 <notifications@github.com> 于 2019年9月3日周二 22:31写道：

**Comment by richardchien** [comment]
由于和 #160 重复，先 close 了
