### ISSUE TITLE
[BUG] access token 验证失败后，websocket服务端显示关闭连接，但是日志内仍然显示增加了一个客户端

### ISSUE THREAD

**Issue by vxray** [richardchien/coolq-http-api#212]
已成功向 7/7 个 WebSocket 客户端推送事件
[2019-09-04 03:46:28.233] [D] [WS] 收到 WebSocket 连接：/
[2019-09-04 03:46:28.233] [D] [WS] 没有提供 Token 或 Token 不符，已关闭连接
[2019-09-04 03:46:38.291] [D] [WS] 开始通过 WebSocket 服务端推送事件
[2019-09-04 03:46:38.294] [I] [WS] 已成功向 8/8 个 WebSocket 客户端推送事件

收到websocket连接以后，日志显示 Token不符合，关闭连接
但是下面的推送增加了一个websocket客户端

**Comment by richardchien** [comment]
那实际 token 不符的客户端收到数据了吗

SniperJack <notifications@github.com>于2019年9月4日 周三10:52写道：

**Comment by vxray** [comment]
> 收到

并没有收到数据，这时候确实是关闭的，但是我还没来得及浏览源代码，我猜测是没有将失败的客户端剔除出去，但是看日志确实是有发送这个动作。

**Comment by richardchien** [comment]
没收到的话应该就是没有删掉连接了，目前应该不是大问题，等闲下来再修吧

SniperJack <notifications@github.com>于2019年9月4日 周三11:27写道：

**Comment by richardchien** [comment]
看了下源码发现这个问题是正在用的 WebSocket 库的问题，准备换一个，进度见 #232

**Comment by Shigma** [comment]
提个小的建议。就是如果验证失败的话能不能直接 403 掉，就不建立连接了呢？因为从接受方的角度来说，如果每次收到的都是 json 还算比较好处理，但明明连接已经成功后却收到了 authorization failed 就显得有些奇怪了……（不知道是不是有其他的考虑？）

**Comment by vxray** [comment]
不好吧，毕竟你不知道是因为什么连接失败的

Shigma <notifications@github.com> 于 2019年12月7日周六 15:39写道：

**Comment by richardchien** [comment]
[v4.14.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.14.0) 已修复
