### ISSUE TITLE
API _send_group_notice 发布群公告 失效了

### ISSUE THREAD

**Issue by KingjZhang** [richardchien/coolq-http-api#213]
API _send_group_notice 发布群公告 失效了
`[2019-09-05 08:15:19.421] [I] [HTTP] 已成功处理一个 API 请求：/_send_group_notice`

既使提示已经成功处理,但也失效了,昨天还是好.重启也不管用,已经更新成最新版本的coolq-http-api以及最新版本的酷Q仍然不行.
但_get_group_notice工作 正常

**Comment by richardchien** [comment]
酷Q 本次更新可能修改了一些 cookies 相关的接口内容，群公告这几个接口是依赖 cookies 的，可能是出了些问题，不能保证在短时间内修复

**Comment by richardchien** [comment]
有群友说这个接口还能用，你可以试试看清理 酷Q 缓存之后重新登录，或者看看是不是接口调用不太对

**Comment by Coxxs** [comment]
新版已推送：5.14.12A (190905) ，试一下是否还有这个问题？

**Comment by KingjZhang** [comment]
好的,感谢.我试试

**Comment by KingjZhang** [comment]
前二天试了,刚才又重启,酷Q又自动更新了,仍然不行. 
现在是5.14.13A(190906)版本的

**Comment by KingjZhang** [comment]
调用_send_group_notice返回 数据如下,` "retcode": 104,    "status": "failed"`,看C++代码是直接调用QQ网站的,可能是QQ屏蔽了接口?

```
{
    "data": [{
        "cn": 0,
        "fid": "12121212211212",
        "fn": 0,
        "msg": {
            "text": "*******",
            "text_face": "*******",
            "title": "群公告"
        },
        "pubt": 1566161906,
        "read_num": 11,
        "settings": {
            "is_show_edit_card": 0,
            "remind_ts": 0,
            "tip_window_type": 0
        },
        "type": 6,
        "u": 12121212,
        "vn": 0
    }],
    "retcode": 104,
    "status": "failed"
}
```

**Comment by richardchien** [comment]
昨天发布了 4.11.0 版本，因为时间原因没有详细看群公告这个接口，不过 `get_cookies` 接口现在可以通过 `domain` 参数获取特定域名下的 cookies，可以参照插件 [源码](https://github.com/richardchien/coolq-http-api/blob/3e3b2447594b2059bd778f869de39947a1e9afda/src/cqhttp/plugins/experimental_actions/experimental_actions.cpp#L319)，尝试自行获取 cookies 来请求对应接口，这里面用到 `web.qun.qq.com` 可以尝试用 `qun.qq.com` 作为 `domain` 参数

**Comment by KirosHan** [comment]
i have the same problem

**Comment by richardchien** [comment]
最新版 v4.12.0 应该已经修复了这个问题，不过下划线接口本身就是不稳定的，不能保证每时每刻都可用，先 close 了
