### ISSUE TITLE
[小问题]CQhttp插件使用的是酷Q Air，无法支持解析CQ Image，我改如何发送图片或者使用酷Q Pro

### ISSUE THREAD

**Issue by yumeTsukiiii** [richardchien/coolq-http-api#218]
使用了代码如下所示
```
     messageFilter {
                condition {
                    message.removeBlank().removePunctuation().contains(
                        Regex(".*(绫濑)*.*(锉刀).*(绫濑)*.*")
                    )
                }

                responser {
                    GroupMessageResponse(
                        reply = "？？？[CQ:image,file=https://imgchr.com/i/nsqnxA]"
                    )
                }
            }

```
我发送了这样的CQ码，无法被解析

**Comment by Coxxs** [comment]
你的图片链接似乎是个网页？图片需要是直链，例如 https://s2.ax1x.com/2019/09/14/nsqnxA.jpg。如果还是不行可以附一下酷Q的日志截图。

**Comment by yumeTsukiiii** [comment]
> 你的图片链接似乎是个网页？图片需要是直链，例如 https://s2.ax1x.com/2019/09/14/nsqnxA.jpg 。如果还是不行可以附一下酷Q的日志截图。

我修改成了您所说的地址，并且酷Q日志如下
![Uploading image.png…]()
但仍然无法发送出图片
![Uploading image.png…]()

**Comment by kj415j45** [comment]
只有 Pro 可以发送图片，现在是 Pro 版本吗

**Comment by yumeTsukiiii** [comment]
> 只有 Pro 可以发送图片，现在是 Pro 版本吗

我使用的是http-api官方文档上说明的docker镜像，它默认使用了酷Q Air，我不清楚可以如何换成Pro版本或者通过其它方式发送图片

**Comment by ExerciseBook** [comment]
@yumeTsukiiii rm cqa.exe
然后复制一个 cqp.exe 进去（

**Comment by yumeTsukiiii** [comment]
> @yumeTsukiiii rm cqa.exe
> 然后复制一个 cqp.exe 进去（

@ExerciseBook 谢谢，不过想请问，这个文件在哪呢emm

**Comment by rikakomoe** [comment]
@yumeTsukiiii docker run -e COOLQ_URL=http://dlsec.cqp.me/cqp-tuling richardchien/cqhttp:latest

**Comment by rikakomoe** [comment]
文档的 Docker > 通过环境变量配置容器的运行 那一节有的

**Comment by yumeTsukiiii** [comment]
> 文档的 Docker > 通过环境变量配置容器的运行 那一节有的

非常感谢！以后我看文档会更仔细一些的！

**Comment by ExerciseBook** [comment]
@yumeTsukiiii 到 cqp.cc 随便下一下就有 cqp.exe 了 😂

**Comment by xtaodada** [comment]
@yumeTsukiiii [酷Q Pro 小i版 <荐>](https://dlsec.cqp.me/cqp-xiaoi) [酷Q Pro 图灵版](https://dlsec.cqp.me/cqp-tuling) [Pro 标准版 <无基础词库>](https://dlsec.cqp.me/cqp-full)
请 😂

**Comment by rikakomoe** [comment]
@xtaodada 这几个链接不错可以考虑加到文档里 @richardchien @Coxxs
