### ISSUE TITLE
上报数据的时候获取不到post过来的数据，

### ISSUE THREAD

**Issue by Koxue** [richardchien/coolq-http-api#22]
上报数据的时候获取不到post过来的数据，

**Comment by richardchien** [comment]
你确定上报地址天的对吗

**Comment by slight-sky** [comment]
你好,可以各个上报数据的样例吗 
**{
"post_type":"message",
"message_type":"message",
"sub_type":"message",
"user_id":"message",
"message":"message"
}**
这样的样例?
如果是这样的话他的字段是什么 我post收不到呢

**Comment by richardchien** [comment]
> {
> "post_type":"message",
> "message_type":"message",
> "sub_type":"message",
> "user_id":"message",
> "message":"message"
> }
> 这样的样例?

就是这样的，见 https://richardchien.github.io/coolq-http-api/#/Post

收不到上报消息可能是上报 URL 填错了吧，或者酷 Q 的运行环境下没法连上那个 URL

**Comment by slight-sky** [comment]
不会的呀 路径和地址都可以访问 
额 这个不能传图片 请问可以QQ交谈吗  我把QQ号发你邮件
