### ISSUE TITLE
在音乐分享中包含符号“♩”导致CQ码嵌套，最终发送失败。

### ISSUE THREAD

**Issue by bltsheep** [richardchien/coolq-http-api#220]
![image](https://user-images.githubusercontent.com/35132976/65225658-82a75c80-db00-11e9-94ca-5fa92bdd033b.png)
从VNC中复制出来的文本如下：
```
?: 308419061 
[CQ:music,audio=https://b.ppy.sh/preview/919268.mp3,content=802s&#44; 6.12*
by Ryuusei Aika [CQ:emoji,id=9833]180,image=https://b.ppy.sh/thumb/919268l.jpg,title=??????????/Ceui,url=https://osu.ppy.sh/s/919268]
```
似乎是存在编码问题导致部分字符变为问号，应该与问题无关。从上面的文本可以看出音符符号在音乐分享中被转换成了`[CQ:emoji,id=9833]`，可能是发送失败的原因。

**Comment by richardchien** [comment]
怎么 close 了😂，说起来我好像一直忘了测试

bleatingsheep <notifications@github.com> 于 2019年9月23日周一 21:31写道：

**Comment by bltsheep** [comment]
应该是酷Q的问题，XX发新版以后就没问题了。
