### ISSUE TITLE
能不能加一个只获取所有好友QQ号的api

### ISSUE THREAD

**Issue by lietxia** [richardchien/coolq-http-api#223]
机器人好友太多/_get_friend_list 不起作用了

**Comment by richardchien** [comment]
@lietxia 不是因为好友多才不起作用，是因为这接口本来就不稳定……

**Comment by ExerciseBook** [comment]
@richardchien 抓群官网接口吧 qwq

**Comment by ExerciseBook** [comment]
来了来了。醋Q内置了船新API。等rc更新吧～

**Comment by richardchien** [comment]
v4.12.0 支持了 酷Q 新提供的获取好友列表接口
