### ISSUE TITLE
开启HTTP服务器成功却不能接收请求?

### ISSUE THREAD

**Issue by Enzymii** [richardchien/coolq-http-api#224]
配置是默认的, 只改了第一行的host..
![image](https://user-images.githubusercontent.com/28684712/66320728-f398a200-e951-11e9-8796-fef794db4046.png)
然后控制台窗口也显示服务器开启成功了..
![image](https://user-images.githubusercontent.com/28684712/66320777-06ab7200-e952-11e9-8537-6f846c4d686f.png)
但是还是访问不能..
![image](https://user-images.githubusercontent.com/28684712/66320677-dd8ae180-e951-11e9-9c58-92d95d6f87c1.png)
然后控制台和log也没有任何其他输出.. 就一直保持跟图二一样..

想问一下是什么情况qwq

**Comment by Enzymii** [comment]
重启了一下电脑就能用了不知道为什么qwq
感觉非常好用啊qwq

**Comment by Enzymii** [comment]
重启了一下电脑就能用了不知道为什么qwq
感觉非常好用啊qwq

**Comment by richardchien** [comment]
应该是端口占用了，5700 端口似乎被某个很普遍的软件用了，建议直接换个端口
