### ISSUE TITLE
长消息无法发送

### ISSUE THREAD

**Issue by DavidDiao** [richardchien/coolq-http-api#226]
稍微长一些的消息发送之后收不到消息，但是插件的响应没报错。小窗和群聊都有这个问题。

**Comment by richardchien** [comment]
@DavidDiao 看 酷Q 日志，插件响应没错说明 酷Q 反馈是成功的

**Comment by DavidDiao** [comment]
酷Q的日志写的也是成功
所以我只能想办法把消息拆开来发？~~我之前用别的机器人的时候咋就没这问题呢~~
https://cqp.cc/forum.php?mod=viewthread&tid=23722 查到了这么一个贴子，我换个号试试吧

**Comment by richardchien** [comment]
@DavidDiao 我觉得你发不了长消息那也多半发不了短消息了……你这个帖子是太久之前的了，没有参考价值，换个号试试看

**Comment by DavidDiao** [comment]
换了个号 发出去了 不愧是腾讯
