### ISSUE TITLE
建议httpapi发一个换名版本

### ISSUE THREAD

**Issue by yuudi** [richardchien/coolq-http-api#227]
大佬好，我有多个程序同时用到httpapi，我希望在一个机器人上同时部署这些程序，但是好像一个httpapi并不能连接多个程序。

我有一个办法不知道可不可行，大佬能不能打包一个分身版，就把httpapi改个名重新打包一下，这样的话一个酷Q上就可以同时运行两个httpapi了。

**Comment by richardchien** [comment]
@yuudi 那要运行三个是不是还要再换个名😂 你这需求用http的话就自己写个中间件做转发，不用http的话就用websocket，随便正向反向都可以同时多个连接

**Comment by yuudi** [comment]
谢谢解答，我试试多个连接
