### ISSUE TITLE
陌生人发来的消息

### ISSUE THREAD

**Issue by genspider** [richardchien/coolq-http-api#228]
当qq开启推广咨询后 陌生人可以发来消息 而插件好像不能回复消息 post_type 为other

**Comment by richardchien** [comment]
@genspider 直接 send_private_msg 不行？

**Comment by genspider** [comment]
显示错误代码 -32
{   "data": null,                                                     "echo": 1648451782,
  "retcode": -35,                                                   "status": "failed"                                              }

**Comment by richardchien** [comment]
这个应该属于 酷Q 的问题，这边大概解决不了，可以去 酷Q 论坛那边提问

**Comment by genspider** [comment]
好的 谢谢
能不能多一个 加载历史消息 的接口
