### ISSUE TITLE
如何发送CQ图片

### ISSUE THREAD

**Issue by ShineWellSnake** [richardchien/coolq-http-api#23]
我的data/image下面有743C29401D05A7D64B96706A5AF2D7A0.jpg.cqimg文件

我使用[CQ:image,file=743C29401D05A7D64B96706A5AF2D7A0.jpg] 并不能发送图片提示错误：
{"status":"failed","retcode":-11,"data":null}
发送文字或者表情都正常~~

**Comment by richardchien** [comment]
可以发一下酷 Q 日志的截图吗，日志等级改成「调试（Debug）」，谢谢

**Comment by ShineWellSnake** [comment]
![kuq](https://cloud.githubusercontent.com/assets/28005777/25390048/f8766f6e-2a04-11e7-902a-0c0483b3ab4f.jpg)
AIR版本不支持。。

**Comment by richardchien** [comment]
尴尬（（

**Comment by ShineWellSnake** [comment]
那怎么办，要下他的收费版本了？

**Comment by richardchien** [comment]
嗯，发图片必须 Pro 版才行

**Comment by ShineWellSnake** [comment]
嗯，感谢，我去了解下他的收费版怎么收费~~ ^_^

**Comment by richardchien** [comment]
嗯嗯
