### ISSUE TITLE
使用CQ码发图片的时候图片大小不能超过4M

### ISSUE THREAD

**Issue by wsjtangy** [richardchien/coolq-http-api#231]
在使用CQ码进行图片发送的时候发现4M以内的图片可以发送,大于4M就无法发送了，这个哪里做了限制吗？

另外，现在插件能不能发送文件？目前遇到需要在群里发excel或者word的需求。没有找到可以支持的方案。

**Comment by richardchien** [comment]
@wsjtangy 这个估计是 酷Q 或者 QQ 那边的限制

**Comment by richardchien** [comment]
@wsjtangy 文件也是不可以发的，目前 酷Q 没支持，如果有这个需求可以去 酷Q 论坛那边提
