### ISSUE TITLE
图片上传失败之后有没有反馈信息

### ISSUE THREAD

**Issue by maborosh** [richardchien/coolq-http-api#233]
有没有图片上传失败之后的反馈信息，文档里面好像没看到。如果没有可以加上这个功能吗？

**Comment by remiliacn** [comment]
这个问题我也经常遇到，感觉是coolQ那边的锅

看CQP的日志有的时候是图片上传失败有的是不是有效图片类型

**Comment by richardchien** [comment]
调用发送返回的 retcode 没有问题吗

**Comment by remiliacn** [comment]
如果信息中既有图片又有文字，文字会被发送出去但是图片有的时候不会。所以retcode似乎调用后没发现什么问题。

一般情况下就是第一次发送如果图片没发送过去，在调用同样的指令重新将在同样路径的图片再发一遍，就能正常显示了。

**Comment by maborosh** [comment]
> 如果信息中既有图片又有文字，文字会被发送出去但是图片有的时候不会。所以retcode似乎调用后没发现什么问题。
> 
> 一般情况下就是第一次发送如果图片没发送过去，在调用同样的指令重新将在同样路径的图片再发一遍，就能正常显示了。

和我的问题一样，最近突然就频繁发生这种情况

**Comment by charles2hang** [comment]
+1 我是直接转base64发送，发送的成功与否毫无规律，但失败居多，失败就显示日志“不是有效的图片，无法发送”，不知道是CQ的锅还是http-api的锅，也是最近才频繁出现

**Comment by momocow** [comment]
@charles2hang 是用 ws 連接嗎？

**Comment by charles2hang** [comment]
@momocow 用的是NodeSDK请求 https://github.com/richardchien/cqhttp-node-sdk  CQ是用Docker部署的

**Comment by richardchien** [comment]
> 一般情况下就是第一次发送如果图片没发送过去，在调用同样的指令重新将在同样路径的图片再发一遍，就能正常显示了。

如果再次遇到，麻烦在第一次发送失败后，看一下 酷Q 日志的报错信息，以及 酷Q `image` 路径下相应的文件是否确实可以打开🤔

**Comment by richardchien** [comment]
> +1 我是直接转base64发送，发送的成功与否毫无规律，但失败居多，失败就显示日志“不是有效的图片，无法发送”，不知道是CQ的锅还是http-api的锅，也是最近才频繁出现

你的问题可能跟楼上的不一样，再次遇到的话，尝试一下在没有连续请求的情况下，独立的测试一次（也就是不要连续发送多个 API 请求），检查相应图片文件是不是可以打开，也可以把 base64 内容以 txt 文档附件的形式上传，我来测试一下（如果不敏感的话）

**Comment by Akyuu** [comment]
我也遇上了类似上面提到的情况，使用base64编码的CQ码发送的图片，CQHTTP插件日志窗口里面没有错误记录，酷Q日志里则是经过15秒左右的等待后报错，提示“数据错误，无法请求发送(-11)”，重复尝试有时会成功，用时也短很多（1秒左右）。

看了下 `CoolQ/data/image` 文件夹下每次请求都生成了对应的图片文件，可以正常打开；成功和失败的时候，生成的文件具有相同的MD5值。

**Comment by richardchien** [comment]
@Akyuu 这个我比较怀疑是你服务器到 QQ 服务器连接不稳定

**Comment by remiliacn** [comment]
我这边测试了一下，我是用`[CQ:image,file=file:///path]`的方式发的图片，这个图片在路径中可以打开，在`/data/image`里面也可以打开，但是图片发出来的时候显示不出来。

coolQ日志会显示**上传失败**。

**Comment by Akyuu** [comment]
> @Akyuu 这个我比较怀疑是你服务器到 QQ 服务器连接不稳定

抓了下包，发现确实是VPS到腾讯服务器的连接出了问题。

具体体现是：腾讯的某个海外节点到我的VPS连接质量很差，上传图片的时候只要随机到那个节点，就会上传失败；随机到其他节点的时候可以正常上传。

**Comment by larvata** [comment]
当同一个带多张图片的消息同时发送到两个群的情况下
如果遇到网络问题 第一个群很可能会收到缺少部分图片的消息 或者 干脆返回-11错误
而第二个群基本上都能正确收到完整的消息

目前我的做法是根据返回值来判断是否要重新发送
但是缺图片的情况下 返回值始终是0 没办法得知是否缺了图

酷q发送图片似乎是先上传图片到qpic.cn然后在去发送消息
不知道这两部能否拆开 确保所有图片都正确上传了再去发消息文本

**Comment by CHFreezer** [comment]
我也遇到了这个问题，确实是网络不稳定造成，但是希望有个上传失败的回调，特别是消息+CQ码图片的时候

**Comment by richardchien** [comment]
消息中同时包含文字和图片，然后图片上传失败的情况，目前 CQHTTP 没有办法从函数返回值判断，需要酷Q那边先解决了
