### ISSUE TITLE
v4.12.x加载失败

### ISSUE THREAD

**Issue by Tarocch1** [richardchien/coolq-http-api#235]
windows server 2012 R2
酷Q 5.15.3A
vc++ 2017 32位运行库，通用C运行库更新均已安装
酷Q v4.12.x无法加载，v4.11可以正常加载
![I}SDV@S~4G2~D2KACW 29SB](https://user-images.githubusercontent.com/15124068/67112362-9d591800-f209-11e9-99e7-aabb5265dd75.png)

**Comment by richardchien** [comment]
v4.12.2 已修复
