### ISSUE TITLE
插件控制台日志显示成功处理 API 请求，但是 QQ 并没有发送群消息

### ISSUE THREAD

**Issue by FETE-CH** [richardchien/coolq-http-api#237]
切换了好几个群，都是没有发送。但是私聊消息却可以，怎么回事？

- 操作系统：Windows 10 1903
- 酷Q： Air 版 5.15.3A(191014)
- 插件：coolq-http-api v4.12.2

**Comment by richardchien** [comment]
@FETE-CH 你的QQ被腾讯限制了，等一段时间，或者换个号试试

**Comment by FETE-CH** [comment]
另一个也是刚注册的账号是正常的，这种情况大概要等多久呢？

**Comment by FETE-CH** [comment]
已经可以了，刚注册到能够发消息过了1个半小时左右
