### ISSUE TITLE
能否在heartbeat事件中包含heartbeat_interval的值

### ISSUE THREAD

**Issue by frankli0324** [richardchien/coolq-http-api#238]
由于最近貌似有检查酷Q的状态是否正常的情况，之前没怎么关心这块emm
按理来说alive的值应当在收到心跳包并检查正常后设置为true，并且在heartbeat_interval后归零为false，但如果我配置好cqhttp这边的heartbeat_interval，自己代码里的超时时间也得修改。
如果上报的事件中就含有heartbeat_interval的值的话，每次就可以以这个值为超时时间

**Comment by richardchien** [comment]
这个有道理，我得想想（

Frank <notifications@github.com>于2019年10月30日 周三23:09写道：

**Comment by richardchien** [comment]
master 分支已经加了，随下个版本发布

**Comment by frankli0324** [comment]
吼！

**Comment by richardchien** [comment]
4.12.3 加上了
