### ISSUE TITLE
如何取得群列表，qq好有列表？

### ISSUE THREAD

**Issue by supmind** [richardchien/coolq-http-api#24]
如题

**Comment by richardchien** [comment]
酷 Q 的 C++ 暂时没有直接获取的接口，所以我也没做，但是网上应该有通过群空间和 QQ 空间来获取群列表和好友列表的办法，你可以自行搜索一下，我的插件这边可以通过 `/get_cookies` 和 `/get_csrf_token` 来获取必要的 cookie 和 token
