### ISSUE TITLE
cqhttp.cc文档中引用链接需要更新

### ISSUE THREAD

**Issue by fred913** [richardchien/coolq-http-api#240]
最今发现，CQ官方文档地址变为了`https://docs.cqp.im/`，不是`https://d.cqp.me/`了，`https://cqhttp.cc/docs/4.12/#/API?id=%E5%93%8D%E5%BA%94%E8%AF%B4%E6%98%8E`等地方的链接需要更改 @richardchien

**Comment by richardchien** [comment]
感谢提醒，已经更新了～
