### ISSUE TITLE
时区设置

### ISSUE THREAD

**Issue by daninedd** [richardchien/coolq-http-api#242]
请问时区配置在哪儿呢？

**Comment by richardchien** [comment]
为什么要设置时区呢？

**Comment by daninedd** [comment]
<img width="475" alt="QQ20191110-000958@2x" src="https://user-images.githubusercontent.com/26319967/68531556-81e7b580-034e-11ea-8e89-8512589b21e4.png">
<img width="623" alt="QQ20191110-001014@2x" src="https://user-images.githubusercontent.com/26319967/68531557-8318e280-034e-11ea-896f-fcf383be0484.png">
docker 日志里显示的时间对不上呢，进入docker里容器本身的时间又是对的

**Comment by richardchien** [comment]
因为虽然是在容器里，但 酷Q 是跑在 Wine 里的，Wine 和容器的 Linux 时区设置大概有不一样，这个你得去看看上游镜像的
Dockerfile 了，自己魔改一下

daninedd <notifications@github.com> 于 2019年11月10日周日 00:12写道：

**Comment by daninedd** [comment]
好的,受教了

**Comment by raymond-coulson** [comment]
我遇到了完全一样的问题，也是docker的时区是正确的，但是cqhttp的时间不对，这个问题可能导致了我现在可以发送私聊消息，但是完全无法发送群聊消息。

**Comment by ExerciseBook** [comment]
@raymond-coulson 能发私聊消息不能发群消息是腾讯风控。
