### ISSUE TITLE
http api 能否支持跨域访问？

### ISSUE THREAD

**Issue by pandolia** [richardchien/coolq-http-api#246]
因为浏览器和服务端的跨域限制，现在无法在网页的 js 脚本中访问 coolq-http-api 。

**Comment by pandolia** [comment]
js 脚本访问 cool-http-api 之前，浏览器会先发送一个 option 请求给服务端。

**Comment by richardchien** [comment]
@pandolia 目前 http 应该是不行，没处理那个 option 请求，你可以试试用 websocket，这个可以的

**Comment by pandolia** [comment]
好的。我先用反向代理吧。

您可以考虑一下，对 option 请求和其他请求的响应都增加下面的 header: 
```
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
```

**Comment by Arnie97** [comment]
是否有必要加个配置项，允许用户自己定义 headers？这样可以 cover 这个问题以及一些其他可能的需求

**Comment by richardchien** [comment]
v4.13.0 已支持，需通过 `enable_cors` 配置项启用

> 允许用户自己定义 headers？

自定义 headers 不太能 cover 这个需求，因为 CORS 需要涉及到 `OPTIONS` 请求，还不是无脑给每个请求响应都加某个自定义 headers
