### ISSUE TITLE
不能发送群消息

### ISSUE THREAD

**Issue by yuxuechao** [richardchien/coolq-http-api#248]
HTTP模式调用send_group_msg 接口无法对群组发送消息，无反应

**Comment by F88888** [comment]
我也是,Docker模式

**Comment by ExerciseBook** [comment]
@F88888 能否详细介绍一下你遇到的问题？是 cqhttp 不理你的请求 // 还是理了但是酷Q没处理 // 还是 酷Q处理了实际上其效果 ？

**Comment by richardchien** [comment]
如果酷Q日志里面有发送的日志，那就是号被风控了，用安卓手机登录发点正常消息之后再试试

**Comment by ztencmcp** [comment]
> 如果酷Q日志里面有发送的日志，那就是号被风控了，用安卓手机登录发点正常消息之后再试试

日志正常，返回消息也是成功了的。这是什么问题呢@richardchien.

**Comment by richardchien** [comment]
@ztencmcp 那就是被风控了。。😂换个号或者手动登录聊聊天看看

**Comment by chenzeZzz** [comment]
我换了 3 个号，也换了 ip，本地也试了，发群消息日志显示成功，但是收不到，单聊是正常的
![image](https://user-images.githubusercontent.com/24696566/69847816-2eb0b500-12b3-11ea-8956-898a6bd68939.png)

**Comment by ExerciseBook** [comment]
@chenzeZzz 风控实锤

**Comment by chenzeZzz** [comment]
> @chenzeZzz 风控实锤

换号换ip都不行呢

**Comment by ExerciseBook** [comment]
@chenzeZzz qwq 我觉得这个问题你抓qq风控工程师问他都回答不了你。
