### ISSUE TITLE
有支持机器人发送图片的接口吗?

### ISSUE THREAD

**Issue by h4ckdepy** [richardchien/coolq-http-api#253]
有支持机器人发送图片的接口吗?文档里面没看见,求助一下。

**Comment by ExerciseBook** [comment]
@h4ckdepy 见 docs.cqp.im 酷Q码一节和 cqhttp 的扩展酷Q码。

**Comment by h4ckdepy** [comment]
> @h4ckdepy 见 docs.cqp.im 酷Q码一节和 cqhttp 的扩展酷Q码。

看完了 但是没搞懂cq码怎么使用  用私聊信息发送的方式吗?直接粘贴CQ码好像响应有误 希望能有个直接点的例子

**Comment by langren1353** [comment]
我测试用CQ码也失败了
`{
	"user_id": 1008611--自己改,
	"message": [{
		"type": "image",
		"data": {
			"url": "https://www.baidu.com/img/bd_logo1.png"
		}
	}]
}`
返回的结果是：
`{
    "data": null,
    "retcode": -33,
    "status": "failed"
}`

**Comment by ExerciseBook** [comment]
@langren1353 -33 错误码对应的文本说明是啥？看看酷Q日志。

**Comment by h4ckdepy** [comment]
> @langren1353 -33 错误码对应的文本说明是啥？看看酷Q日志。

我擦 怎么使用CQ码的啊 我还以为是http://127.0.0.1:5700/send_private_msg?user_id=1234567&message=[CQ:face,id=14] 这样

**Comment by ExerciseBook** [comment]
@h4ckdepy 等于号要urlencode。= 和 url参数的 = 冲突了。

**Comment by langren1353** [comment]
@ExerciseBook 酷Q的日志如何查看呢
--
@h4ckdepy 这个是另一种调用方式都是那个，但是确实我没有成功

**Comment by ExerciseBook** [comment]
@langren1353 酷Q悬浮窗右键（

**Comment by h4ckdepy** [comment]
> @langren1353 酷Q悬浮窗右键（

找不到与目标账号的关系 啥意思

**Comment by langren1353** [comment]
@ExerciseBook 
![image](https://user-images.githubusercontent.com/14857127/70228585-8c4f7080-178f-11ea-8778-b2acbe006716.png)
文字描述是：Air版本不支持该操作P_P还有解决方案吗

**Comment by rikakomoe** [comment]
@langren1353 充钱解决

**Comment by h4ckdepy** [comment]
> @ExerciseBook
> ![image](https://user-images.githubusercontent.com/14857127/70228585-8c4f7080-178f-11ea-8778-b2acbe006716.png)
> 文字描述是：Air版本不支持该操作P_P还有解决方案吗

我解决了  air可以的 我就是air

**Comment by ExerciseBook** [comment]
@h4ckdepy 那就不要私聊X。酷Q不允许主动发起私聊。

**Comment by h4ckdepy** [comment]
> @h4ckdepy 那就不要私聊X。酷Q不允许主动发起私聊。

成功了！ 刚刚qq写错了 我就是想做个社工库 输入名字拿照片这样

**Comment by langren1353** [comment]
@h4ckdepy 可以交流下吗；mail:1353464539@qq.com

**Comment by h4ckdepy** [comment]
> @h4ckdepy 可以交流下吗；mail:[1353464539@qq.com](mailto:1353464539@qq.com)

ok

**Comment by ExerciseBook** [comment]
@h4ckdepy 这边建议您阅读一下酷Q tos 8.1.2 呢 https://docs.cqp.im/about/tos/

**Comment by lancelock** [comment]
> > @ExerciseBook
> > ![image](https://user-images.githubusercontent.com/14857127/70228585-8c4f7080-178f-11ea-8778-b2acbe006716.png)
> > 文字描述是：Air版本不支持该操作P_P还有解决方案吗
> 
> 我解决了 air可以的 我就是air

请问怎么解决的？我也是相同的问题，docker部署的

**Comment by ExerciseBook** [comment]
@lancelock Air 不能使用。

你换成 Pro 版本就行辣。
```
rm CQA.exe
```
然后复制一个 `CQP.exe` 进去


如果还不行的话就去 dockerhub 里查查启动参数。

**Comment by mrmarktyy** [comment]
哪里可以下载到CQP.exe? 
官方论坛已经不能注册了

**Comment by ExerciseBook** [comment]
@mrmarktyy 看cqhttp文档里的 酷Q码（CoolQ Code） 一节

**Comment by mrmarktyy** [comment]
@ExerciseBook 
> 酷 Q Air 无法发送 image 码（同一消息的其它文本可正常发出）

我现在用的是Air 发送图片遇到-33错误代码
应该是Air不支持的原因

**Comment by ExerciseBook** [comment]
@mrmarktyy 那就只能去下个 CQP 回来。

cq官网随缘开放注册。

**Comment by mrmarktyy** [comment]
![image](https://user-images.githubusercontent.com/1808651/82621570-d08bdb80-9c1e-11ea-89dd-1481f71bf04b.png)
下载好CQP回来后 重命名为CQA.exe 就行了吗？
我看还有一些key和配置文件

**Comment by ExerciseBook** [comment]
@mrmarktyy 不用重命名 放到和 cqa 同一个目录下就行了

**Comment by mrmarktyy** [comment]
@ExerciseBook 
我刚碰到了一个奇怪的问题。。 之前一直是可以的

现在我不能用meta.$send给群发消息了，回复个人消息是可以的。
app.sender.sendGroupMsg也一样，群收不到消息。

我在COOLQ的日志里是可以看到回复消息那条日志。但是QQ里就是收不到。

大哥有碰到过类似的问题吗？

**Comment by ExerciseBook** [comment]
@mrmarktyy 用多了之后你会发现你用QQ原版客户端也会出现这个情形。当然更多的时候是你体验过，但是没发现。

**Comment by mrmarktyy** [comment]
那我的理解是 这是QQ那边对COOLQ的限制吧？
有没有什么解决的办法呢？

@ExerciseBook

**Comment by ExerciseBook** [comment]
@mrmarktyy https://docs.cqp.im/manual/faq/

**Comment by mrmarktyy** [comment]
谢谢！

**Comment by ExerciseBook** [comment]
@mrmarktyy 不客气~

**Comment by mrmarktyy** [comment]
@ExerciseBook 大佬能分享一个PRO的exe么， 我email联系了站长 没有回复我。

**Comment by Sobte** [comment]
@mrmarktyy test

**Comment by ExerciseBook** [comment]
@mrmarktyy https://hub.docker.com/r/coolq/wine-coolq/
https://github.com/CoolQ/docker-wine-coolq
 康康这个readme

里面有个 
http://dlsec.cqp.me/cqp-full

**Comment by mrmarktyy** [comment]
好勒 多谢

**Comment by ExerciseBook** [comment]
@mrmarktyy 不客气

**Comment by mrmarktyy** [comment]
@ExerciseBook 想购买个授权码，但是论坛不能注册。。 有点头疼啊

**Comment by Sobte** [comment]
@mrmarktyy 论坛会不定期开放注册的，耐心等待吧，或者开发插件，发布社区，申请开发者授权也可以拿到免费的激励授权
