### ISSUE TITLE
win10的支持貌似不太完美

### ISSUE THREAD

**Issue by chunjie008** [richardchien/coolq-http-api#254]
我用的是win10有更新就更新的那种。
 安装了 VC++ 2019 ，还是报-103，重启也没用

**Comment by ExerciseBook** [comment]
-103 是酷Q错误码。
主要还是看前面的 getLastError 后面跟的错误码。

顺：我个人觉得还是系统问题（也许是你的系统被加料了）。AWS 的 Server 2019 安装上 VC++ Runtime 2017 可以正常工作。

**Comment by richardchien** [comment]
装32位（x86）版的 vc++2017 运行库

游超 <notifications@github.com>于2019年12月6日 周五12:18写道：

**Comment by ExerciseBook** [comment]
@richardchien 说个题外话（X
RC的电脑貌似就是 Win 10 的（

**Comment by richardchien** [comment]
目前运行库这个问题看到很多反馈，可能确实有点问题，等后面有空会找一下问题在哪

**Comment by ExerciseBook** [comment]
@richardchien 我其实上次在aws装了个白板windows 为什么我带上个vc++2015就能跑了。这有点奇怪。

**Comment by chunjie008** [comment]
> -103 是酷Q错误码。
> 主要还是看前面的 getLastError 后面跟的错误码。
> 
> 顺：我个人觉得还是系统问题（也许是你的系统被加料了）。AWS 的 Server 2019 安装上 VC++ Runtime 2017 可以正常工作。

我把VC++卸载了一个一个的试还是不行，也许是我酷q是5.15.5的问题。因为以前我是成功运行过，那时候酷q版本忘了，http api用的4.11.0 这酷q5.15.5 http api 4.12.3怎么样都不行。

**Comment by richardchien** [comment]
我在纯的 Windows Server 2012 上试了下，应该可以确定没有问题，Windows 10 就更不会出问题了，不仅是我的开发环境，也是很多用户的开发环境，请确认一下你安装运行库的是不是文档中给出的 [链接](https://aka.ms/vs/16/release/vc_redist.x86.exe) 中下载的最新版，全名叫「适用于 Visual Studio 2015、2017 和 2019 的 Microsoft Visual C++ 可再发行软件包」，也可以在 [这里](https://support.microsoft.com/zh-cn/help/2977003/the-latest-supported-visual-c-downloads) 下载

**Comment by richardchien** [comment]
因为时间比较久远，issue 先 close 了，如果问题还存在的话，请随时 reopen
