### ISSUE TITLE
在哪里可以获取到登录机器人的qq号啊~

### ISSUE THREAD

**Issue by h4ckdepy** [richardchien/coolq-http-api#255]
在http通信的时候怎么获取到机器人的qq号 我记得我看到过 现在没找到~~~

**Comment by h4ckdepy** [comment]
> 在http通信的时候怎么获取到机器人的qq号 我记得我看到过 现在没找到~~~

**Comment by richardchien** [comment]
有找到吗，是用 `/get_login_info` 接口
