### ISSUE TITLE
升级到 CoolQ Pro 5.15.5 后程序崩溃（HTTP API 4.12.3）

### ISSUE THREAD

**Issue by Shigma** [richardchien/coolq-http-api#256]
以下是报错信息：
![image](https://user-images.githubusercontent.com/33423008/70339015-fdbf1a00-1888-11ea-8842-7dfdc5408e55.png)

**Comment by Shigma** [comment]
刚刚研究了一下，是重启 CoolQ 时发生的问题，CoolQ 提示自动更新，但 HTTP API 的日志窗口并没有关闭。手动关闭后再次重新载入就能正常工作了。应该不是很严重的问题。

**Comment by richardchien** [comment]
嗯，日志这块确定有个问题，等后面有空会修

Shigma <notifications@github.com> 于 2019年12月7日周六 00:33写道：

**Comment by richardchien** [comment]
[v4.14.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.14.0) 尝试做了修复（其实就是 catch 了异常），如果再次发现相同问题请 reopen
