### ISSUE TITLE
用get_image方法图片下载失败

### ISSUE THREAD

**Issue by ys278099744** [richardchien/coolq-http-api#259]
环境：腾讯云、centos7、酷qPro,
我想把群消息里面的图片下载下来，
使用get_image?file=8C6A26D6297A40EFE64C10795F98078D.jpg
返回内容：
`{
data: null,
retcode: 102,
status: "failed"
}`
有人知道怎么回事吗？

**Comment by ExerciseBook** [comment]
@ys278099744 z？kk酷Q地址。

**Comment by richardchien** [comment]
> { data: null, retcode: 102, status: "failed" }

这个报错一般是酷Q那边没成功，需要看看酷Q日志
