### ISSUE TITLE
bug反馈 ，用postman post数据的时候 酷q会错误退出

### ISSUE THREAD

**Issue by supmind** [richardchien/coolq-http-api#26]
用postman 测试的时候，header 数据如下 `{"Authorization":"token Mgep4rV49rM8Jf","message":"5555","user_id":"17570xxxxx"}` 然后酷q就出现错误退出了

**Comment by richardchien** [comment]
你这个数据是放在哪的，按理说 `Authorization` 是 header，`message` 和 `user_id` 在 body……

**Comment by richardchien** [comment]
应该这样：

![image](https://cloud.githubusercontent.com/assets/5317095/25778298/79a858ba-332c-11e7-87f8-eae2b06521f2.png)
![image](https://cloud.githubusercontent.com/assets/5317095/25778300/7df2d90e-332c-11e7-9491-adfdd3315c2b.png)

**Comment by supmind** [comment]
是直接放在headers 里面了，重现不了了，不知道那几次是怎么回事
