### ISSUE TITLE
酷qpro 能够用插件推mp3文件给qq吗

### ISSUE THREAD

**Issue by h4ckdepy** [richardchien/coolq-http-api#261]
酷qpro 能够用插件推mp3文件给qq吗

**Comment by richardchien** [comment]
@h4ckdepy 我记得是可以直接发的，需要安装语音组件

**Comment by ExerciseBook** [comment]
酷Q 可以通过语音功能（就是语音聊天）发送音频，但是不能发送文件。

**Comment by h4ckdepy** [comment]
> 酷Q 可以通过语音功能（就是语音聊天）发送音频，但是不能发送文件。

好惨  我就想实现酷q 发文件   只能发图片和音频对吧

**Comment by ExerciseBook** [comment]
曲线救国 H T T P
