### ISSUE TITLE
send_group_msg 是失效了吗，私聊发送成功的

### ISSUE THREAD

**Issue by wnight9527** [richardchien/coolq-http-api#264]

**Comment by wnight9527** [comment]
{'data': {'message_id': 1093}, 'retcode': 0, 'status': 'ok'}
返回是这个

**Comment by ExerciseBook** [comment]
https://docs.cqp.im/manual/faq/

详见以上

**Comment by JonTree** [comment]
腾讯最近弄了异地登陆无法发送群消息，只能发私人消息，把号在那个上面挂几天就好了

**Comment by Shigma** [comment]
感觉是风控问题而不是 CQHTTP 的问题呢
