### ISSUE TITLE
发送不了图片，不管是私聊还是群聊。另外如果json中放了三段内容，中间一段是图片，只会发送第一句话。。。

### ISSUE THREAD

**Issue by wnight9527** [richardchien/coolq-http-api#265]

**Comment by ExerciseBook** [comment]
在？看看醋Q日志。

**Comment by liang1024** [comment]
必须要酷QPro才能发图片吧？？？发图片是收费吧？

**Comment by richardchien** [comment]
> 发送不了图片，不管是私聊还是群聊

可能是因为用的是 酷Q Air，发图片需要 Pro，建议看下 酷Q 日志

> 如果json中放了三段内容，中间一段是图片，只会发送第一句话

这是 酷Q 的实现逻辑，目前 CQHTTP 也无能为力

**Comment by ExerciseBook** [comment]
@richardchien 醋Q可以图文混排吧。
