### ISSUE TITLE
撤回消息接口失效

### ISSUE THREAD

**Issue by langzicx** [richardchien/coolq-http-api#266]
```
{
"data": None,
"retcode": -99,
"status": "failed"
}
```
[delete_msg](https://cqhttp.cc/docs/4.13/#/API?id=delete_msg-%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF)
[send_like](https://cqhttp.cc/docs/4.13/#/API?id=delete_msg-%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF)

这2个报的一样

**Comment by ExerciseBook** [comment]
-99 : 请使用 酷Q Pro 以解锁这个功能。

**Comment by ExerciseBook** [comment]
-99 : 请使用 酷Q Pro 以解锁这个功能。

**Comment by langzicx** [comment]
好的，感谢

**Comment by ExerciseBook** [comment]
@langzicx 不客气

**Comment by ExerciseBook** [comment]
@langzicx 下次遇到类似的问题先去看看酷Q日志，那里会带有中文提示的。

**Comment by langzicx** [comment]
@ExerciseBook  好的,对酷Q不熟悉一直看的 http插件的日志😄,现在找到了
![https://ask.qcloudimg.com/draft/6210528/oj5blm610i.png](https://ask.qcloudimg.com/draft/6210528/oj5blm610i.png)
