### ISSUE TITLE
有没有扩展开发对接文档

### ISSUE THREAD

**Issue by langzicx** [richardchien/coolq-http-api#267]
需要用http 接口调用一些dll ，有好的办法解决吗？

**Comment by richardchien** [comment]
我建议是直接在你的开发语言那边调用 DLL 的

如果一定要开发 CQHTTP 扩展的话，目前只有 [cqhttp-ext-starter](https://github.com/richardchien/cqhttp-ext-starter) 这个 starter 项目，暂时没有文档。可以参考 [cqhttp-ext-long-polling](https://github.com/richardchien/cqhttp-ext-long-polling) 和 [cqhttp-ext-cleaner](https://github.com/richardchien/cqhttp-ext-cleaner)。不过，因为之前 CQHTTP 的构建脚本有过修改，它本身的构建过程可能和扩展的构建过程有点不一致，可能需要自行做些改动
