### ISSUE TITLE
回复消息如何获取原始内容

### ISSUE THREAD

**Issue by jianmj** [richardchien/coolq-http-api#268]
针对一条消息回复asdfdfff ，回复消息后，获取的报文内容为，
{"anonymous":null,"font":1385848,"group_id":903491028,"message":"[CQ:at,qq=2848857079] asdfdfff","message_id":59317,"message_type":"group","post_type":"message","raw_message":"[CQ:at,qq=2848857079] asdfdfff","self_id":2848857079,"sender":{"age":0,"area":"","card":"","level":"冒泡","nickname":"风语","role":"owner","sex":"unknown","title":"","user_id":823584051},"sub_type":"normal","time":1578013162,"user_id":823584051}
是否有办法 获取到  针对哪条消息进行回复。

**Comment by momocow** [comment]
@jianmj 目前無法取得，底層酷Q尚未支持回覆。
