### ISSUE TITLE
建议更新CQP.lib文件以便支持新的CQ_getGroupMemberList接口

### ISSUE THREAD

**Issue by waylonwang** [richardchien/coolq-http-api#27]
5.8.2和5.8.3支持了获取群成员列表的API，建议升级coolq-http-api提供最新的支持，谢谢！
请参考https://cqp.cc/t/32975

**Comment by richardchien** [comment]
嗯，我之前也自己做了个新版的 CQP.lib，不过一直懒，没更新这个……我现在做吧，稍等一下（

**Comment by richardchien** [comment]
好了，请更新到 1.1.3 版本

**Comment by richardchien** [comment]
话说朋友有兴趣加一下 QQ 交流群（201865589）吗，方便交流一些
