### ISSUE TITLE
未收到服务器响应是什么原因呢？

### ISSUE THREAD

**Issue by JakinMiao** [richardchien/coolq-http-api#270]
![DFC2489D5E478E27214ECE68385C4D62](https://user-images.githubusercontent.com/20729564/71986410-6bcf7600-3267-11ea-83eb-bfb393e32627.jpg)
调起机器人发送信息报错

**Comment by richardchien** [comment]
这个是 酷Q 没法出去，可能你的号被腾讯限制了，见 https://docs.cqp.im/manual/faq/
