### ISSUE TITLE
Authorization头设置了token仍然报401错误

### ISSUE THREAD

**Issue by hundunzhidian** [richardchien/coolq-http-api#271]
RT，使用get方式把token扔到url里面就没问题,f12抓包如下，求解
**Request URL: http://XXXXXXXX:5700/send_group_msg?
Request Method: POST
Status Code: 401 Unauthorized
Remote Address: XXXXXXXX:5700
Referrer Policy: no-referrer-when-downgrade
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Authorization: Bearer 9d90XXXXXXXXXXXX
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 39
Content-Type: application/json**

**Comment by richardchien** [comment]
看一下 酷Q 日志，在 CQHTTP 启动的时候应该输出了读到的配置，看有没有正确读到 `token`

**Comment by momocow** [comment]
@hundunzhidian Authorization: Token kSLuTF2GC2Q4q4ugm3 X-Self-ID: 123456 


> 注意：这里本应该是 Authorization: Bearer kSLuTF2GC2Q4q4ugm3（和插件作为服务端的校验保持一致），但由于历史上的某次升级时忘记把这里的 Token 改为 Bearer，并且如果现在修改可能会对已有代码造成破坏，因此决定保持为 Token 不变。

https://cqhttp.cc/docs/4.13/#/CommunicationMethods?id=api-%E8%B0%83%E7%94%A8

**Comment by richardchien** [comment]
@momocow 应该不是这个问题，因为插件所谓服务端的情况下，是两种都可以的

**Comment by hundunzhidian** [comment]
> @momocow 应该不是这个问题，因为插件作为服务端的情况下，是两种都可以的

看了下日志，好像没啥毛病，我用get方式把token丢在url后面是可以的

**Comment by hundunzhidian** [comment]
> @momocow 应该不是这个问题，因为插件作为服务端的情况下，是两种都可以的

刚刚测了下，还真就把Bearer改成Token 就可以用了

**Comment by momocow** [comment]
@hundunzhidian 請問一下你的插件版本是？

**Comment by hundunzhidian** [comment]
> @hundunzhidian 請問一下你的插件版本是？

4.7.0,好老的版本了...

**Comment by richardchien** [comment]
@hundunzhidian 那你应该换最新版本，或者在文档右上角选4.7
