### ISSUE TITLE
_get_vip_info接口不管查什么人等级都是111

### ISSUE THREAD

**Issue by tobycroft** [richardchien/coolq-http-api#273]
RT，这个是最近出现的，不知道是api问题还是coolq本身的问题，以下测试情况

1.未加机器人好友，未在同一个群：111
2.未加机器人好友，在同一个群：111
3.加了机器人好友，在同一个群：111

以上三种情况，通过_get_vip_info接口查询用户等级，原来能显示正确的等级数字，现在就成这样了

**Comment by richardchien** [comment]
![image](https://user-images.githubusercontent.com/5317095/72229965-5357b680-35ed-11ea-8b1a-64c278f532a1.png)

我这边试了下，似乎是可以的要不你换个号试下

这个接口不是 酷Q 提供的，是腾讯的 web 接口，在 CQHTTP 里面调用的，确实可能会不稳定
