### ISSUE TITLE
对Websocket极度不友好

### ISSUE THREAD

**Issue by KawaiiZapic** [richardchien/coolq-http-api#274]
反向Websocket收到消息时直接向酷Q推HTTP回复格式是不可行的,那么是不是没有办法像HTTP一样在Websocket里做出回复?  
能否在上报事件时包含更完整的信息(如群消息包含群信息)?Websocket再次调用API可以说是非常麻烦了.

**Comment by momocow** [comment]
@KawaiiZapic 快速響應在 ws 連接沒有作用的，請直接調用 API。回覆和 API 請求的格式不也只差了一點點，怎麼說麻煩了(？)

**Comment by richardchien** [comment]
因为 WebSocket 不像 HTTP 那样有去有回，所以不能直接像那样快速响应，建议是另外调用 API

如果你真的想用 HTTP 快速回复那套，可以用隐藏接口 [`.handle_quick_operation`](https://cqhttp.cc/docs/4.13/#/API?id=-handle_quick_operation-%E5%AF%B9%E4%BA%8B%E4%BB%B6%E6%89%A7%E8%A1%8C%E5%BF%AB%E9%80%9F%E6%93%8D%E4%BD%9C)

**Comment by richardchien** [comment]
从我个人的使用体验来看，如果你用的编程语言和 WebSocket 库支持 `async`、`await` 这种异步，还是比较容易弄得很友好的（至少和 HTTP 一样），例如 [python-aiocqhttp](https://github.com/richardchien/python-aiocqhttp) 的 HTTP 和 WebSocket 使用体验几乎一致；但如果你的语言并没有 `async` 语法支持，必须基于 `on_message` 回调之类的来做，我甚至不建议使用 WebSocket

**Comment by KawaiiZapic** [comment]
> 因为 WebSocket 不像 HTTP 那样有去有回，所以不能直接像那样快速响应，建议是另外调用 API
> 
> 如果你真的想用 HTTP 快速回复那套，可以用隐藏接口 [`.handle_quick_operation`](https://cqhttp.cc/docs/4.13/#/API?id=-handle_quick_operation-%E5%AF%B9%E4%BA%8B%E4%BB%B6%E6%89%A7%E8%A1%8C%E5%BF%AB%E9%80%9F%E6%93%8D%E4%BD%9C)

我的第一个问题我已经理解了.  

那在上报消息时可否包含更完整的信息?Websocket在处理过程中再次调用API并收返回值简直麻烦到爆炸,不方便与普通事件分开.  
P.S:我写的后端是事件驱动的,调用API发生返回也会成为一个事件,但事件之间是非同步的.如果需要获得返回就需要截断默认事件冒泡,还得想办法把返回从另一个事件里递给当前事件,又麻烦又不优雅.

**Comment by richardchien** [comment]
> 那在上报消息时可否包含更完整的信息?

这个可以考虑，不过我觉得这不是根本之策（你总不可能永远不调用 API……

可以尝试封装一个可以传入回调函数的方法（例如 [这个](https://github.com/crazywhalecc/CQBot-swoole/blob/master/src/cqbot/mods/Admin.php#L49)），或者用类似 future 的东西把 API 调用同步化（在需要调用的地方创建 future 并等待，CQHTTP 的 WebSocket 支持 `echo` 字段作为唯一标识，在 API 调用的 on message 回调里设置 future 的 result，从而导致调用方等待结束）

**Comment by KawaiiZapic** [comment]
> > 那在上报消息时可否包含更完整的信息?
> 
> 这个可以考虑，不过我觉得这不是根本之策（你总不可能永远不调用 API……
> 
> 可以尝试封装一个可以传入回调函数的方法（例如 [这个](https://github.com/crazywhalecc/CQBot-swoole/blob/master/src/cqbot/mods/Admin.php#L49)），或者用类似 future 的东西把 API 调用同步化（在需要调用的地方创建 future 并等待（CQHTTP 的 WebSocket 支持 `echo` 字段作为唯一标识），在 API 调用的 on message 回调里设置 future 的 result，从而导致调用方等待结束）

非常感谢.   
  
API调用是肯定要调用的,但是不一定要取返回值.如果能减少后端与插件之间的数据交换那是最好的.  
  
echo这个特性我想起来了,我看看能不能用于方便的截断事件冒泡再获得返回.调用API可以考虑用协程来实现同步不阻塞.
