### ISSUE TITLE
只要使用配置文件，coolq就会崩溃

### ISSUE THREAD

**Issue by hectorqin** [richardchien/coolq-http-api#275]
![image](https://user-images.githubusercontent.com/14220132/72487159-0c193200-3848-11ea-93d4-f105954a21c7.png)

![image](https://user-images.githubusercontent.com/14220132/72487181-1804f400-3848-11ea-8697-cf238a50e318.png)

**Comment by richardchien** [comment]
@hectorqin 这个格式不对，请看 https://cqhttp.cc/docs/4.13/#/Configuration?id=%E4%BD%BF%E7%94%A8-json-%E6%A0%BC%E5%BC%8F%EF%BC%8C%E5%9C%A8%E5%8D%95%E4%B8%AA%E6%96%87%E4%BB%B6%E4%B8%AD%E5%AD%98%E6%94%BE%E5%A4%9A%E4%B8%AA%E8%B4%A6%E5%8F%B7%E7%9A%84%E9%85%8D%E7%BD%AE

**Comment by hectorqin** [comment]
好吧，access_token 要放在用户账号下
