### ISSUE TITLE
发送消息时，文字和图片一起发送时的BUG

### ISSUE THREAD

**Issue by chenxuxin188** [richardchien/coolq-http-api#276]
文字和图片一起发送的话，如果图片上传失败，返回的还是发送成功，然后文字发送出去，不带图片。

**Comment by chenxuxin188** [comment]
我不知道这个是酷Q的问题还是这个http api的问题。。日志里头看到的提示是一个√，然后提示图片发送失败。然后websocket里收到的返回值还是0

**Comment by richardchien** [comment]
@chenxuxin188 可以发一下酷Q日志截图吗

**Comment by shitianshiwa** [comment]
我也见到过这个，除了把图片拆出来单独发送外，没有别的方法解决。
单独发图片可以检测到上传失败错误，不过由于文字可能无法与图片对应，被迫放弃了文字和图片分开发送，现在完全看运气了。
不过，还是加了有几张图片来提醒是否丢图。
https://github.com/richardchien/coolq-http-api/issues/233

**Comment by chenxuxin188** [comment]
> @chenxuxin188 可以发一下酷Q日志截图吗

没办法……因为只出现过一次，而且有一段时间了。我现在直接把这个改了一下，让文字在图片之后发，如果图片发送失败就不发文字就没事了。

**Comment by chenxuxin188** [comment]
> @chenxuxin188 可以发一下酷Q日志截图吗

酷Q日志里头，单发送图片失败前面的符号是一个X，但是带了文字信息的话会变成一个√，其他都一样。然后后边还跟着一个消息发送成功的提示，消息内容是本来应该和图片一起发送的文字内容。

**Comment by chenxuxin188** [comment]
> 我也见到过这个，除了把图片拆出来单独发送外，没有别的方法解决。
> 单独发图片可以检测到上传失败错误，不过由于文字可能无法与图片对应，被迫放弃了文字和图片分开发送，现在完全看运气了。
> 不过，还是加了有几张图片来提醒是否丢图。
> #233

行吧，之前没看到这个。。   看来是酷Q的问题  这东西还挺烦的

**Comment by ExerciseBook** [comment]
检查一下你是不是 Pro ？
