### ISSUE TITLE
v2.1.0配置文件无效

### ISSUE THREAD

**Issue by Ray-Eldath** [richardchien/coolq-http-api#28]
在`app/io.github.richardchien.coolqhttpapi`目录下**手动**（也就是没有自动生成）创建`config.cfg`文件并配置了`port=5000`，但访问`5000`端口却访问不到，依然是默认端口。
配置项可能未生效。

以上，
Ray Eldath.

**Comment by richardchien** [comment]
你是使用 docker 运行的吗？还是 Windows？另外可以发一下配置文件内容吗

**Comment by Ray-Eldath** [comment]
WIndows运行。
配置文件：
```
[general]
host=127.0.0.1
port=5000
post_url=http://127.0.0.1:5050/avalon/v0/post_url
post_message_format=string
```
目前是访问`5000`端口不存在，监听`http://127.0.0.1:5050/avalon/v0/post_url`无消息。
但是**访问默认的`5700`端口就可以**。
如何解决？

**Comment by richardchien** [comment]
`post_url` 这个参数有没有生效呢？

**Comment by Ray-Eldath** [comment]
没有。因为监听`http://127.0.0.1:5050/avalon/v0/post_url`无消息。
（`port`也没有生效啊，只有默认值是可用的=-=）

**Comment by richardchien** [comment]
那酷Q的路径上有没有中文之类的？以及，系统语言是什么？控制面板-时钟、语言和区域-区域-管理-非Unicode程序的语言是什么？

**Comment by richardchien** [comment]
哦对了，你的酷Q根目录下有没有出现乱码加 `config.cfg` 结尾的文件名？

**Comment by Ray-Eldath** [comment]
没有...
`config.cfg`文件还是我手动创建的

**Comment by richardchien** [comment]
可以方便加一下 QQ 群 201865589 然后私聊吗，这边似乎不能上传文件，不好给你测……

**Comment by richardchien** [comment]
哦可以 zip…… 你来试一下换这个 cpk，然后请求 http://ip:5700/test，看下返回什么，以及酷Q的 Debug 日志
[io.github.richardchien.coolqhttpapi.cpk.zip](https://github.com/richardchien/coolq-http-api/files/1082558/io.github.richardchien.coolqhttpapi.cpk.zip)

**Comment by Ray-Eldath** [comment]
**问题已经解决。**
原因是因为目录中含中文...
感激不尽。
（以前版本好像是可以中文的？）

**Comment by richardchien** [comment]
我也不太确定，以前没有测试过中文路径，版本更新也对编码做了一些调整，可能确实会出问题，我后面再多测试测试吧。解决的话，我就先关闭 issue 了～

**Comment by richardchien** [comment]
ohshit，原来你已经关了（（
