### ISSUE TITLE
能不能增加一个反向 WebSocket 连接成功的事件？

### ISSUE THREAD

**Issue by Wybxc** [richardchien/coolq-http-api#281]
当前的生命周期事件只支持 HTTP 上报，使用反向 WebSocket 时很难进行一些初始化操作。

**Comment by richardchien** [comment]
会考虑，不过需要等等

**Comment by richardchien** [comment]
[v4.14.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.14.0) 已加入此事件
