### ISSUE TITLE
/get_friend_list接口拿不到企业版QQ好友列表

### ISSUE THREAD

**Issue by ly8051033** [richardchien/coolq-http-api#282]
/get_friend_list对于普通版的QQ可以拿到好友列表，但是企业版QQ拿到的data为空
![FABE4647-0BF6-447e-8274-2E719F917632](https://user-images.githubusercontent.com/35070566/73918290-5009cf00-48fc-11ea-9af1-ed23beeb1ebd.png)

**Comment by ExerciseBook** [comment]
Reference: https://cqp.cc/t/46961

**Comment by richardchien** [comment]
这种一般是 酷Q 那边的问题，建议去 酷Q 社区问

**Comment by ly8051033** [comment]
> 这种一般是 酷Q 那边的问题，建议去 酷Q 社区问

嗯，发现问题了，酷Q日志显示企点QQ新增好友后是被当做陌生人增加的

**Comment by ExerciseBook** [comment]
的确神奇，看看xx回不回复了。
