### ISSUE TITLE
/get_friend_list可否增加一个不取缓存的参数

### ISSUE THREAD

**Issue by ly8051033** [richardchien/coolq-http-api#284]
QQ好友列表有更新的话获取好友列表接口总是取不到最新的，取的是缓存，可否对于该接口增加一个字段no-cache来判断是否取缓存，或者是给一个清理缓存的接口呢？

**Comment by ExerciseBook** [comment]
回复过了：https://cqp.cc/t/46989

**Comment by ExerciseBook** [comment]
检查了一下酷Q原生api的参数列表。

只有 `getFriendList` 有备注，`getStrangerInfo` 没有备注一项。看来只能等等Q刷新缓存了，具体缓存时间我真不知道是多少。
