### ISSUE TITLE
重装系统后莫名上报事件失败可能是什么原因？

### ISSUE THREAD

**Issue by Night12138** [richardchien/coolq-http-api#287]
刚刚翻了一遍issue 发现基本没有遇到相同问题的，唯一一个很相似的是因为设置了全局的all_proxy，但是我刚刚检查过环境变量没有这个问题
系统Windows 2019 coolq air 5.15.5A 插件版本4.14
日志
`[2020-03-06 08:33:08.473] [I] [日志] 日志控制台开启成功
[2020-03-06 08:33:08.553] [I] [HTTP] 开启 HTTP 服务器成功，开始监听 http://[::]:5700
[2020-03-06 08:33:08.553] [I] [重启] HTTP API 插件重启成功
[2020-03-06 08:34:02.847] [W] [HTTP] HTTP 上报地址 http://127.0.0.1/push_ser/api/ajaxReceiveQQ.php 无法访问`
已经检查过本地浏览器是可以访问的
还有个很奇怪的现象是每次处理都花了特别长时间，长达60s左右 有时候70s有时候40s，然后再过一会就变0.03s(可能直接异常返回了)不知道这些信息会不会使问题定位更准确一些
感谢。

**Comment by ExerciseBook** [comment]
可以考虑在网页服务器日志里看看 cqhttp 的请求有没有啥问题？

**Comment by Night12138** [comment]
> 可以考虑在网页服务器日志里看看 cqhttp 的请求有没有啥问题？
服务器日志有个301的重定向，重定向至443端口和带域名的网址了，这和我最早配置的https时候一致，但是不知道为什么重装系统后就不正常了，配置回带域名的请求http服务器没有记录到
日志
`2020-03-06 00:56:20 127.0.0.1 POST /push_ser/api/ajaxReceiveQQ.php - 80 - 127.0.0.1 CQHttp/4.14.0 - 301 0 0 0`
会重定向至带域名的443端口，但是网页甚至外网访问这个网址都是正常的（出于安全暂时不能贴域名）

**Comment by Night12138** [comment]
但是带域名的443的访问服务器没有被记录到

**Comment by Night12138** [comment]
哇真的迷了！那位老兄是因为设置了all_proxy才导致上报异常的，而我这边却是因为没设置all_proxy……这可太奇怪了……刚刚尝试设置了下all_proxy的环境变量就特么正常了……太迷了

**Comment by ExerciseBook** [comment]
可以试一下 no_proxy 环境变量，把某一些地址设置在排除范围内 qwq
![image](https://user-images.githubusercontent.com/6327311/76071219-db947f80-5fd0-11ea-94e1-dfbee0596c59.png)

**Comment by Night12138** [comment]
> 可以试一下 no_proxy 环境变量，把某一些地址设置在排除范围内 qwq
> ![image](https://user-images.githubusercontent.com/6327311/76071219-db947f80-5fd0-11ea-94e1-dfbee0596c59.png)

谢谢老兄！这个彻底解决了，刚刚把proxy服务器端口关了后也能正常上报而且速度快了1s（之前估计是绕了proxy导致处理时间在2s左右。
