### ISSUE TITLE
消息拦截功能

### ISSUE THREAD

**Issue by 572614737** [richardchien/coolq-http-api#288]
现在我二次开发的应用在处理了消息后，排在coolq http接口后边的应用还会处理一遍这个消息，想请教一下这个拦截消息的功能现在可以实现吗，就是用http接口处理之后的消息，排在http接口后边的应用就不能处理这个消息了，还请赐教

**Comment by richardchien** [comment]
HTTP 上报的话，可以直接给 CQHTTP 返回 JSON 响应：

```json
{ "block": true }
```

来拦截事件

**Comment by 572614737** [comment]
Hi&nbsp;Richard Chien，
&nbsp; &nbsp; &nbsp; &nbsp; 非常感谢您的解答，还想再请教一下，我在nonebot的API文档中并没有看到有关返回JSON{"block": true}的API，这个响应我可以如何实现呢？



谢谢！




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Richard Chien"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 上午10:11
收件人:&nbsp;"richardchien/coolq-http-api"<coolq-http-api@noreply.github.com&gt;;
抄送:&nbsp;"STM32F407ZGT6"<572614737@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [richardchien/coolq-http-api] 消息拦截功能 (#288)




HTTP 上报的话，可以直接给 CQHTTP 返回 JSON 响应：
 { "block": true }
 
来拦截事件

**Comment by ExerciseBook** [comment]
nonebot走的是 websocket :thinking:

**Comment by richardchien** [comment]
NoneBot 不行😂，做不到

**Comment by 572614737** [comment]
好的，感谢解答！
期待NoneBot后续更新会增加这项功能~
