### ISSUE TITLE
linux使用了最新版插件,在某群测试出问题

### ISSUE THREAD

**Issue by 188700679** [richardchien/coolq-http-api#289]
在某个群,request,notice都是正常的,而message在日志里看不到上报消息,也获取不到.....
只有message类型获取不到

但是其他几个群,一切正常.

老版本的在coolq最新版的pro下,会提示缺失组件,无法启动,并不是指语音组件

**Comment by ExerciseBook** [comment]
```
在某个群,request,notice都是正常的,而message在日志里看不到上报消息,也获取不到.....
只有message类型获取不到
```
常见情况
1. 机器人登陆了PCQQ（我觉得不像，因为你提到了有些群可以收的到）
2. 机器人被关闭了获取请求信息的功能（如QQ群加群设置、QQ群不允许某些管理员处理加群申请）

```
老版本的在coolq最新版的pro下,会提示缺失组件,无法启动,并不是指语音组件
```
1. 无解，就算是 Windows 下也无解。（是系统环境问题）

**Comment by richardchien** [comment]
收不到特定群的消息，有没有可能是你在手机上屏蔽了那个群，或者设置了事件过滤器然后忘了

**Comment by 188700679** [comment]
我在登录和未登录PCQQ的情况下,都试过


这个群,加群,退群,是notice上报类型,能正常获取,request类型也正常


message类型就获取不到,在coolq里的日志也看不到上报.


1.检查了一下,这个机器人QQ号从来没在手机上登录过,因为最近在把他打包成php类库,插件也使用一年了,自己开发,所以比较熟悉,截断器是肯定没有设置的
2.机器人并没有被关闭请求信息功能,这个群比较熟悉,也没被限制,只是单纯的收不到message类型的上报信息,就是获取不到任何人说话内容
3.可以主动在这个群内发送消息


其他群的任何功能都正常


去年开始使用插件的时候,一直把插件保存到网盘,虽然后面安装了几次coolq,但都是使用的这个老版本的插件,
一直稳定运行在任何群(包括这个有问题的群),最后一次在linux运行了半年,直到今年2月份.


因为某些原因使用了最新版本的coolq pro,也用了最新版本的插件,这个问题才报出来,


我会再测试一次,换旧一点的版本再看看原因


在coolq的运行日志里看不到上报信息,我估计也可能是coolq的原因


继续跟进


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Richard Chien"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 上午10:19
收件人:&nbsp;"richardchien/coolq-http-api"<coolq-http-api@noreply.github.com&gt;;
抄送:&nbsp;"lonely"<188700679@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [richardchien/coolq-http-api] linux使用了最新版插件,在某群测试出问题 (#289)




收不到特定群的消息，有没有可能是你在手机上屏蔽了那个群，或者设置了事件过滤器然后忘了

**Comment by 188700679** [comment]
今天测试了五次,发现了问题,解决了,

测试版本,新版coolq/pro,最新版httpapi
测试环境docker

1.把httpapi放入coolq里,然后在vnc面板启动插件

2.插件会生成data文件,并提示去修改qq.json文件

3.当修改好配置文件后,在应用里重载应用,100%提示(检测到某应用非法调用........)

如果这时候去docker stop coolq  && docker start coolq

会有非常大的概率提示windows script contro组件缺失

在这里卡了三次,卡了一天

最后通过vnc(非快速重启,快速重启也容易出问题),退出,重进,成功启动httpapi

加上昨晚,测试10次了
