### ISSUE TITLE
楼主接口封装的不错 ,我试用了还可以, 就是给群里陌生人发消息,对方接收不到

### ISSUE THREAD

**Issue by BianJian** [richardchien/coolq-http-api#29]
陌生人加群, 我send_private_msg 过去, 对方接收不到,  当对方发聊天给我的情况下,  我再进去就可以收到, 我不晓得啥原因.

**Comment by richardchien** [comment]
这个确实是发出不出去的，是酷 Q 的问题，你可以看酷 Q 的日志，会提示「未找到和联系人的关系」之类的，对方给你发了之后你才能发
