### ISSUE TITLE
关于群消息无法发送

### ISSUE THREAD

**Issue by Sakura0w0** [richardchien/coolq-http-api#291]
"status":"ok"返回OK，但是实际上没有发送消息到群里，私聊可以正常发送

**Comment by YadominJinta** [comment]
Same issue.
Seems that tencent blocked CoolQ.
[Coolq BBS](https://cqp.cc/t/47677)

**Comment by Sakura0w0** [comment]
> Same issue.
> Seems that tencent blocked CoolQ.
> [Coolq BBS](https://cqp.cc/t/47677)

我在手机上登录这个QQ号还可以在群里正常发消息，不知道是不是因为VPSIP共享的原因

**Comment by ExerciseBook** [comment]
@YadominJinta 这个是腾讯风控保护

https://docs.cqp.im/manual/faq/
