### ISSUE TITLE
请问是否支持发送语音和图片？

### ISSUE THREAD

**Issue by kiochan** [richardchien/coolq-http-api#292]
大家好
我在 [API描述](https://cqhttp.cc/docs/4.14/#/API?id=api-%E5%88%97%E8%A1%A8) 中找到了关于图片和语音的接收相关的API，但没有找到发送相关的API，请问是我找错文档了还是需要搭配其他插件实现？

**Comment by ExerciseBook** [comment]
@kiochan d.cqp.im 见 酷Q码一节。若还不理解你发条语音/图片给机器人看看机器人日志收到的是啥。

**Comment by kiochan** [comment]
https://cqhttp.cc/docs/4.14/#/CQCode?id=%E5%8F%91%E9%80%81%E7%BD%91%E7%BB%9C%E5%9B%BE%E7%89%87%E6%88%96%E8%AF%AD%E9%9F%B3
感谢你，我根据你说的在文档中找到了。
