### ISSUE TITLE
/set_friend_add_request 获取不到flag

### ISSUE THREAD

**Issue by 188700679** [richardchien/coolq-http-api#293]
/set_friend_add_request 处理加好友请求,这条API需要对方加好友时的上报flag,
但是上报数据里,并没有flag

贴出上报数据
'{"notice_type":"friend_add","post_type":"notice","self_id":2442459484,"time":1583907566,"user_id":188700679}'

**Comment by richardchien** [comment]
你这个上报是 notice 类型，也就是加好友成功的通知，可能你不小心开了同意所有请求
