### ISSUE TITLE
在pro中集成插件加载时插件报错

### ISSUE THREAD

**Issue by bystart** [richardchien/coolq-http-api#295]
在pro中集成插件加载时插件报错 导致无法使用该插件  服务器是win7系统

**Comment by richardchien** [comment]
报错截图来一下？

**Comment by needhourger** [comment]
相同的问题
服务器win sever 2012
酷q版本最新
cqhttp 4.14.1

![image](https://user-images.githubusercontent.com/32973369/76701389-ab00c400-66fb-11ea-8f03-8b64175d3107.png)

**Comment by ExerciseBook** [comment]
126 错误：请安装 vc 运行库，见文档的部署部分。
