### ISSUE TITLE
5800端口突然起不来了，求大神支招

### ISSUE THREAD

**Issue by Stone-wh** [richardchien/coolq-http-api#297]
![image](https://user-images.githubusercontent.com/21095779/76825473-101bfd00-6855-11ea-8472-4d3186b55d70.png)
目前放容器里面，从昨天开始，程序突然挂了。

**Comment by richardchien** [comment]
你这容器重新创建了。。正确的方法应该是把 酷Q 目录作为 volume 挂载进去
