### ISSUE TITLE
在dockers中加载应用报错

### ISSUE THREAD

**Issue by REMIAZK** [richardchien/coolq-http-api#298]
![image](https://user-images.githubusercontent.com/50099600/77026218-1f728600-69ce-11ea-94f0-16c1da656c20.png)
日志上显示开始监听5700端口但无法访问

**Comment by richardchien** [comment]
建议尝试重启容器

**Comment by REMIAZK** [comment]
已经重启过了还是不行

**Comment by ExerciseBook** [comment]
![image](https://user-images.githubusercontent.com/6327311/77253365-95a80e80-6c94-11ea-8761-2a0014ed4a6a.png)
docker 里的 5700 开放出来了吗？

**Comment by REMIAZK** [comment]
已经开了
话说有人用docker成功运行了吗？

**Comment by haowen-li** [comment]
我可以的

**Comment by REMIAZK** [comment]
最后换成window成功了
