### ISSUE TITLE
无法发送cq码

### ISSUE THREAD

**Issue by XYZliang** [richardchien/coolq-http-api#299]
如题，今天第一次接触此机器人和插件。
使用插件发送cq码却一直无法发送。
比如http://192.168.0.66:5700/send_group_msg?group_id=1090504374&message=[CQ:face,id=14]
http://192.168.0.66:5700/send_group_msg?group_id=1090504374&message=[CQ:at,qq=1424625705]
返回均为
{
    "data": null,
    "retcode": 100,
    "status": "failed"
}
根据插件的帮助文档，发现是说缺少参数？请问具体是哪缺少了呢？发送非cq码文本没问题（第一次使用的小白）

**Comment by XYZliang** [comment]
看官方介绍，酷q air是支持@人的吧

**Comment by ExerciseBook** [comment]
等于号要转义

**Comment by XYZliang** [comment]
好的谢谢。我尝试一下

> message中的等于号要转义
> 
> ![图片](https://user-images.githubusercontent.com/6327311/77076900-6e9cd300-6a2f-11ea-8a8f-ff4186b212fa.png)
> 
> 正确的例子：
> 
> ```
> http://192.168.0.66:5700/send_group_msg?group_id=1090504374&message=%5BCQ%3Aat,qq%3D1424625705%5D1111
> ```

**Comment by XYZliang** [comment]
> http://192.168.0.66:5700/send_group_msg?group_id=1090504374&message=%5BCQ%3Aat,qq%3D1424625705%5D1111

感谢，已经解决

**Comment by ExerciseBook** [comment]
偷懒写法：直接套一层 URLEncode 到 message 上就可。
