### ISSUE TITLE
我收到的群聊json数据似乎没有消息内容

### ISSUE THREAD

**Issue by HaroldYu** [richardchien/coolq-http-api#3]
![image](https://cloud.githubusercontent.com/assets/19909103/22640426/892f2d44-ec8d-11e6-9274-e7d2ff874680.png)
先测试了一下似乎是这样的，但是私聊消息有内容。
![image](https://cloud.githubusercontent.com/assets/19909103/22640497/dda0964c-ec8d-11e6-84db-705bbb9325e3.png)

**Comment by richardchien** [comment]
我找到问题了，https://github.com/richardchien/coolq-http-api/blob/master/appmain.cpp#L331，这构造 json 的地方最后少了个 s:s，但是这两天没电脑不好改，如果你能自己编译的话自己先改一下吧

**Comment by richardchien** [comment]
https://github.com/richardchien/coolq-http-api/releases/tag/v1.0.1b3 这个 release 修复了这个 bug
