### ISSUE TITLE
可否提供基于旧版本vc++的此插件

### ISSUE THREAD

**Issue by sxyandapp** [richardchien/coolq-http-api#30]
**机器是server 2008 x64的系统，之前使用此插件一直没有问题**，今天更新后发现加载插件失败，最终定位了问题是vs c++库版本过低。
下载了作者提供的连接中的vc++的安装包，结果安装失败，提示缺少一个KB2999226这个补丁。然而费了9牛2虎之力，也没在机器上安装成功这个插件。尝试使用windows update更新操作系统，可能由于server的操作系统限制太严格或公司网络等原因，无法更新。
因为此机器是公司的重要服务器，也不便安装其他操作系统。所以恳请作者提供基于之前的VC++版本的插件，感谢。

**Comment by richardchien** [comment]
2.0.0 版本开始进行了大量重构，代码全部基于很多 C++ 新语法，用 VC++ 2010 工具集已经没法编译了，而在 1.x 的代码中实现 2.x 的一些功能会非常费劲，所以暂时可能真的没办法出兼容旧版运行库的插件，如果确实没有办法升级系统的话，那建议使用 [1.1.6 版本](https://github.com/richardchien/coolq-http-api/releases/tag/v1.1.6) 吧（注意有一些功能可能和当前文档有所出入）

**Comment by sxyandapp** [comment]
谢谢
