### ISSUE TITLE
能否考虑在用ws进行事件上报的时候，增加一个标识。

### ISSUE THREAD

**Issue by takayama-lily** [richardchien/coolq-http-api#301]
ws通信由于不是一对一的，所以无法进行快速回复。
能否考虑在用ws进行事件上报的时候，增加一个标识，这样在回复中携带标识，就能进行快速回复了。

**Comment by richardchien** [comment]
@takayama-lily 你可以使用 .handle_quick_operation 隐藏方法

**Comment by takayama-lily** [comment]
@richardchien 我没有注意有这个隐藏方法。
这个方法不是挺正常的吗，为啥要设置成隐藏的。

**Comment by richardchien** [comment]
@takayama-lily 因为主要是给 SDK 实现快速响应用的，考虑不太适合暴露给正常用户
