### ISSUE TITLE
post_url无法访问

### ISSUE THREAD

**Issue by LaureatePoet** [richardchien/coolq-http-api#306]
## 命令
```
docker run -ti --rm --name cqhttp \
	-v /root/coolq-data:/home/user/coolq \
	-p 9000:9000 \
	-e VNC_PASSWD=****** \
	-p 5700:5700 \
	-e COOLQ_ACCOUNT=QQnum \
	-e CQHTTP_POST_URL=http://[公网ip]:8080 \
	-e CQHTTP_SERVE_DATA_FILES=yes \
	richardchien/cqhttp:latest
```
[控制台输出文本](https://paste.ubuntu.com/p/RyNJpHjttZ/)

## 报错
5700端口可以监听，刚开始容器可以**正常运行**，后来报错

```
localhost - - [25/Mar/2020 20:42:49] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
localhost - - [25/Mar/2020 20:42:49] connecting to: 127.0.0.1:5911
[2020-03-25 13:42:57.481] [I] [日志] 日志控制台开启成功
[2020-03-25 13:42:57.486] [I] [HTTP] 开启 HTTP 服务器成功，开始监听 http://[::]:5700

[2020-03-25 13:45:07.846] [W] [HTTP] HTTP 上报地址 http://公网ip:8080 无法访问
```

## 环境
云服务器（华为云）
Ubuntu 18.04 LTS 

----
求大佬解救，本人挺小白的，不知道这样的情况如何解决。
 * 是切换 ip吗，试试用公网ip还是私有ip，还是设置端口。
 * 如果是设置端口的话，安全组设置 是 设置*入安全规则* 还是*出安全规则*

谢谢大佬

**Comment by richardchien** [comment]
应该是需要开安全组，入规则吧

**Comment by LaureatePoet** [comment]
我测试了公网ip、私有ip、localhost；端号8080，8090 还是都不可以，日志都显示的一样
```
[2020-03-25 13:45:07.846] [W] [HTTP] HTTP 上报地址 http://ip:8080 无法访问
```

**Comment by readLemon** [comment]
请问。我也有如上的问题，我检测了一下，是post_url的那个端口没有跑起来。但是不知道为什么没有跑起来。命令是  
docker run -ti -d --name cqhttp -v ~/coolq:/home/user/coolq \
-p 9000:9000 \
-p 5700:5700 
-e COOLQ_ACCOUNT=**** \
 -e CQHTTP_POST_URL=http://服务器公网ip:31092 \
-e CQHTTP_SERVE_DATA_FILES=yes \
richardchien/cqhttp:4.12.0  
我甚至是关了防火墙，同时也加了安全组的

**Comment by Fb-dtalker** [comment]
请问有人解决了吗？我这边是直接本地机子开http的，
"post_url": "http://127.0.0.1:8080/coolq"
然后有监听8080/coolq的web程序，但是同样也是
[2020-04-01 19:01:18.324] [W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080/coolq 无法访问

监听8080的用的是go语言，但是并没有请求进来
http.HandleFunc("/coolq", myHandle)
http.ListenAndServe(":8080", nil)

求教(感谢)

**Comment by 26z1a** [comment]
根据[https://stackoverflow.com/a/24326540](this one) for now在linux机器上只能加上 `--network="host"` 然后以127.0.0.1访问host
