### ISSUE TITLE
发送图片失败, 提示文件名不合法

### ISSUE THREAD

**Issue by haowen-li** [richardchien/coolq-http-api#307]
coolq pro和插件都是最新的, 平台是ubuntu
发送时酷q日志报告:
文件名不合法, 无法发送! (file:///home/usr/xxxx/xyz.png)
看文档里说用URI格式, 我是这么写的:
[CQ:image,file=file:///home/usr/xxxx/xyz.png]
os.path.exists('/home/usr/xxxx/xyz.png')返回的是True
谢谢~

**Comment by ExerciseBook** [comment]
@haowen-li wine 环境路径貌似用的不是这个格式

**Comment by richardchien** [comment]
Wine 里面要用 `Z:\home\user\coolq`，具体可以在酷Q悬浮窗点开酷Q文件夹看到路径

**Comment by haowen-li** [comment]
原来是这样, 那么如果图片不放在coolq文件夹里可以吗? 这样的话在Wine里似乎就无法访问了, 我用的是你的另一个项目nonebot, 打算把图片放在那边的文件夹里...

**Comment by ExerciseBook** [comment]
你能把路径问题理对就可

**Comment by richardchien** [comment]
@haowen-li 你可以直接用 docker 的 volume 映射把宿主机上的文件夹挂载到容器内的 `/home/user/coolq/data/image`，图片放在这里面，然后直接用文件名发图

**Comment by haowen-li** [comment]
谢谢, 问题解决了, 就是有点绕...

**Comment by railannad** [comment]
请问你那条报错"来源"是HTTP API还是酷Q？我也遇到了这个问题
