### ISSUE TITLE
docker中重启cqhttp或者cq容器sessionId没有变导致无法发送消息

### ISSUE THREAD

**Issue by zhangmrit** [richardchien/coolq-http-api#309]
反向ws
一切正常以后，重启cqhttp应用或者容器，消息无法发出，调试发现sessionId没变，但是上报的sessionId已经变了

**Comment by zhangmrit** [comment]
在windows客户端是正常的，重启插件或者cq都没影响

**Comment by richardchien** [comment]
CQHTTP 原生没有「sessionId」这个概念，建议去咨询你使用的 SDK 或框架作者
