### ISSUE TITLE
下载CA证书失败,wss协议无法连接上

### ISSUE THREAD

**Issue by hakiGithub** [richardchien/coolq-http-api#310]
[2020-03-27 12:25:47.252] [I] [反向WS] 正在下载 CA 证书文件，这只会在第一次启动时进行，如果耗时较长，请在配置文件中更换 更新源
[2020-03-27 12:25:47.537] [W] [反向WS] 下载 CA 证书文件失败，可能导致无法 WSS
错误码：336396564，将尝试重连
浏览器可以使用wss和ws连接上服务器
---------------------------------------------
若采用ws协议连接则返回错误码：10009
请问大佬们，有什么解决办法？

**Comment by richardchien** [comment]
尝试手动下载 https://github.com/richardchien/coolq-http-api-release/blob/master/assets/cacert.pem 这个文件到 `酷Q/data/app/io.github.richardchien.coolqhttpapi/tmp/cacert.pem` 然后重启 CQHTTP 看看
