### ISSUE TITLE
docker 里目录错误

### ISSUE THREAD

**Issue by cc2cc** [richardchien/coolq-http-api#313]
在docker里运行的插件，本来配置文件应该是/home/uer/coolq/data/app/io.github.richardchien.coolqhttpapi
不知道为啥配置文件都是调用的/home/uer/coolq/app/io.github.richardchien.coolqhttpapi，插件卸载重装后还是这样

**Comment by ExerciseBook** [comment]
@cc2cc 醋Q优先加载 app/appid 若不存在才加载 data/app/appid 。如果想让他不加载 app/appid ，那就删掉 app/appid 。

**Comment by richardchien** [comment]
因为 docker 镜像很久没更新，用的还是旧的路径，解决方案看楼上

**Comment by richardchien** [comment]
更新一下，在最新版本的镜像里面，已经使用新的插件数据路径了，容器启动时会把旧的拷贝到新路径下

**Comment by cc2cc** [comment]
我已经用官方的最新的docker里安装插件的方式解决了目录的问题了，谢谢
