### ISSUE TITLE
Max times should be 20 as SVIP

### ISSUE THREAD

**Issue by hsowan-me** [richardchien/coolq-http-api#317]
![image](https://user-images.githubusercontent.com/55872984/77930785-e398c400-72dd-11ea-9f09-ff426c18ac20.png)

**Comment by richardchien** [comment]
如果 酷Q 支持的话，那么你传 20 应该就行，如果测试可行的话，麻烦回复一下，我改下文档

**Comment by hsowan-me** [comment]
Failed.

**Comment by richardchien** [comment]
那就先 close 了
