### ISSUE TITLE
是否有点赞的api

### ISSUE THREAD

**Issue by h4ckdepy** [richardchien/coolq-http-api#320]
想问一下有没有点名片赞的api啊

**Comment by ExerciseBook** [comment]
https://cqhttp.cc/docs/4.14/#/API?id=send_like-%E5%8F%91%E9%80%81%E5%A5%BD%E5%8F%8B%E8%B5%9E

**Comment by h4ckdepy** [comment]
sorry！！没看见我眼瞎了我靠
