### ISSUE TITLE
发送网络图片的时候增加超时

### ISSUE THREAD

**Issue by blacktunes** [richardchien/coolq-http-api#321]
发送网络图片的时候，有时候因为网络较差会下载非常久导致后面需要发送的消息阻塞了，能不能增加超时取消

**Comment by richardchien** [comment]
如果是用 HTTP 或 WebSocket 接口发的，可以尝试在配置里把 `server_thread_pool_size` 改大，如果是反向 WebSocket，可以把 `thread_pool_size` 改大

**Comment by richardchien** [comment]
[v4.15.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.15.0) 加入了超时参数
