### ISSUE TITLE
图片缓存未更新的问题

### ISSUE THREAD

**Issue by takayama-lily** [richardchien/coolq-http-api#324]
CQ码发送网络图片的文档里有以下内容
> ……则可以在 CQ 码中加入参数 cache=0 来禁用缓存（仅本次有效）

加上cache=0后，缓存的指向还是旧图片(真的是仅本次有效了)，
必须每次都加cache=0才能获取最新图片，无法使用缓存，降低了性能。
希望是cache=0更新一次后，能自动更新该图片缓存。

目前在获取qq头像和群头像时遇到此问题。

**Comment by ExerciseBook** [comment]
没看懂表达的是啥意思。

我的理解是 cache=0 之后和 cache=1 效果一致？

**Comment by takayama-lily** [comment]
意思是cache=1目前永远指向第一次获取的那张图
希望输入cache=0可以指向新图片

例如获取qq头像的地址
http://q1.qlogo.cn/g?b=qq&s=640&nk=qq号
头像偶尔会变更，但是不频繁，不能使用缓存很可惜

**Comment by richardchien** [comment]
来试试 [v4.15.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.15.0) 吧
