### ISSUE TITLE
阿里云服务器noVNC无法连接，failed to connect to server

### ISSUE THREAD

**Issue by KoyomiKun** [richardchien/coolq-http-api#325]
我在docker run这个插件，但noVNC connect的时候显示Failed to connect to server，请问如何解决

**Comment by richardchien** [comment]
尝试：

1. 清除浏览器缓存
2. 删除 docker 容器重新创建
3. 检查阿里云安全组
4. 检查 noVNC 端口是否打开（9000）

**Comment by KoyomiKun** [comment]
Tks, 是我自己配置的问题
