### ISSUE TITLE
普通版酷Q无法加载这个插件

### ISSUE THREAD

**Issue by mcfenmap** [richardchien/coolq-http-api#332]
一串警告之后全部点了是，但酷Q还是无法加载插件，也没有任何报错信息。难道这个插件只能酷Q Pro版才能用吗？？

https://i.loli.net/2020/05/03/tf82wkciVm1Wlyu.png

**Comment by Sobte** [comment]
请按照文档下载，并安装vc
https://cqhttp.cc/docs/4.15/#/?id=%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by richardchien** [comment]
> 一串警告之后全部点了是

可能某一个“是”是提示你去下载语音组件，然后启动过程就停了
