### ISSUE TITLE
通过nonebot调用API clean_data_dir()时报错

### ISSUE THREAD

**Issue by haowen-li** [richardchien/coolq-http-api#333]
按照文档里说的要给出参数名 (清理的目录名，支持 image、record、show、bface)
但是给了以后会说参数应该只有2个而不是3个, 不知道是哪里有问题?
我的用法是这样
```
botNone = nonebot.get_bot()
botNone.clean_data_dir('image')
botNone.clean_data_dir('record')
```

还有就是清理目录的原理是啥?会把所有文件和下面的文件夹也删掉吗? 因为映射了一些要发送的图片到image目录下面的一些文件夹, 所以不想全部删掉...

顺便请教一下怎么在不关掉酷q的情况下清理coolqpro/data/账号名/ 里面的日志? 越积越多没几天就几百m了, 谢谢!

**Comment by richardchien** [comment]
调用 API 要用命名参数，而不是位置参数

**Comment by haowen-li** [comment]
问题解决了!
请问有什么办法清除日志吗?  还有就是清除目录要是能指定一些内容不删除就好了

**Comment by richardchien** [comment]
日志不好清除，需要重启酷Q。

这个清理功能只是一个简单实现，如果你需求很复杂，建议自己写脚本定时清理。
