### ISSUE TITLE
拒绝群邀请时，拒绝理由reason字段填了没用

### ISSUE THREAD

**Issue by takayama-lily** [richardchien/coolq-http-api#335]
api是set_group_add_request
type是add，拒绝申请的时候，reason字段有效
type是invite，拒绝拉群的时候，reason字段未反应

**Comment by ExerciseBook** [comment]
@takayama-lily 因为QQ手机版本身也没这个功能吧

**Comment by takayama-lily** [comment]
CQ本来就不支持吗

**Comment by ExerciseBook** [comment]
在请求种类（邀请/请求）和反馈类型（同意/拒绝）中只有 拒绝入群请求 有效。
应该是手机版QQ本身也没这个功能。
