### ISSUE TITLE
获取群成员列表似乎不是实时的。

### ISSUE THREAD

**Issue by gfhfhoo** [richardchien/coolq-http-api#338]
如题，在用了另一个作者的simple-robot后，发现似乎列表不是更新及时的。

**Comment by ExerciseBook** [comment]
酷Q会在以下的几种情况下更新群列表

1. 群成员变动（新增/修改）
2. 酷Q觉得是时候刷新缓存了
3. 刚开酷Q（存疑）
4. 有管理员变动（存疑）

**Comment by gfhfhoo** [comment]
> 酷Q会在以下的几种情况下更新群列表
> 
> 1. 群成员变动（新增/修改）
> 2. 酷Q觉得是时候刷新缓存了
> 3. 刚开酷Q（存疑）
> 4. 有管理员变动（存疑）

刚开酷Q我试了试 有几率更新，但是大部分情况是不更新的

**Comment by ExerciseBook** [comment]
这个问题并不是 cqhttp 可以控制的，核心还是看 酷Q 本体是怎么管理缓存。

**Comment by gfhfhoo** [comment]
> 这个问题并不是 cqhttp 可以控制的，核心还是看 酷Q 本体是怎么管理缓存。

感谢回答。

**Comment by ExerciseBook** [comment]
不客气。
