### ISSUE TITLE
如何解决多个应用同时使用一个qq号时，需要区分http api端口的问题

### ISSUE THREAD

**Issue by icaruszezen** [richardchien/coolq-http-api#339]
rt

**Comment by richardchien** [comment]
可否具体一点

**Comment by icaruszezen** [comment]
比如说我有两个应用都需要使用http api，一个应用监听9000端口，一个应用监听8000端口。我需要打开两个监听不同端口的http，需要怎么写配置文件

**Comment by icaruszezen** [comment]
找到了一个分身版，貌似完美解决了问题

**Comment by richardchien** [comment]
可以使用正向 WebSocket 来用多个应用连接到同一个 CQ

**Comment by wukoudada** [comment]
多个应用使用同一个qq号，不是会强制下线吗？除非采用不同的协议。话说cq目前之前哪些协议啊，如果cq想采用非安卓协议，应该在哪里配置呢？

**Comment by ExerciseBook** [comment]
这里指的多个应用是 多个基于 cqhttp 的应用程序 :joy:

**Comment by wukoudada** [comment]
emmm

**Comment by railannad** [comment]
> 找到了一个分身版，貌似完美解决了问题

你好，可否分享一下分身版？我也有要用两个插件的需求

**Comment by ExerciseBook** [comment]
@railannad https://github.com/yuudi/yobot/blob/master/documents/install/Windows-portable.md 
这里有一个

**Comment by railannad** [comment]
> @railannad https://github.com/yuudi/yobot/blob/master/documents/install/Windows-portable.md
> 这里有一个

感谢大佬

**Comment by ExerciseBook** [comment]
@railannad 不客气
