### ISSUE TITLE
您好 请问 酷Q程序有公网，python服务无公网，这种可以建立通信么

### ISSUE THREAD

**Issue by Rladmsrl** [richardchien/coolq-http-api#340]
python要放在内网服务器，没法开公网访问，酷q可以放在我自己的nas上，这种方式可以使用么 谢谢

**Comment by Rladmsrl** [comment]
> python要放在内网服务器，没法开公网访问，酷q可以放在我自己的nas上，这种方式可以使用么 谢谢

补充下，python服务可以访问外网

**Comment by KawaiiZapic** [comment]
@Rladmsrl 按道理,只要http能和cq互联,cq能登录,那就没问题.

**Comment by richardchien** [comment]
你这个需求比较适用 [正向 WebSocket 通信方式](https://cqhttp.cc/docs/#/CommunicationMethods?id=%E6%8F%92%E4%BB%B6%E4%BD%9C%E4%B8%BA-websocket-%E6%9C%8D%E5%8A%A1%E7%AB%AF)
