### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by LuffyQAQ** [richardchien/coolq-http-api#341]
无法下载cpk文件，百度网盘也失效

**Comment by ExerciseBook** [comment]
@LuffyQAQ 没问题 我能下载（确信）

**Comment by LuffyQAQ** [comment]
我的Windows确实没法下载，开梯子也没法下载，不过我用linux的wget就可以下载了

**Comment by SkinCrab** [comment]
@LuffyQAQ 没问题 我也能下载（确信）

**Comment by ExerciseBook** [comment]
@LuffyQAQ 能成功就好，问题不大，如果还有啥问题的话可以加QQ群或者是tg群寻求帮助。

**Comment by LuffyQAQ** [comment]
> @LuffyQAQ能成功就好，问题不大，如果还有啥问题的话可以加QQ群或者是tg群寻求帮助。

好的，谢谢，我先研究研究
