### ISSUE TITLE
文档的百度网盘下载链接挂了

### ISSUE THREAD

**Issue by fred913** [richardchien/coolq-http-api#344]
[此处](https://cqhttp.cc/docs/4.15/#/)的百度网盘链接挂了
![图片.png](https://i.loli.net/2020/05/30/bZueJXpk73NGaoI.png)

**Comment by ExerciseBook** [comment]
```此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！```

**Comment by richardchien** [comment]
OK，链接换掉了
