### ISSUE TITLE
链接被拒绝，原因：Authentication failure

### ISSUE THREAD

**Issue by EffyLu** [richardchien/coolq-http-api#347]
嗨，您好

我们在访问 ip:9000 端口的时候，输入密码提示【链接被拒绝：Authentication failure】

请问有什么解决办法吗，谢谢。

**Comment by ExerciseBook** [comment]
@EffyLu 看文档

**Comment by EffyLu** [comment]
多谢回复，可以说明是哪个文档吗，抱歉我们没有找到。

**Comment by ExerciseBook** [comment]
@EffyLu 在通信方式里 https://cqhttp.cc/docs/4.15/#/CommunicationMethods
有关于身份认证相关的说明

取决于你的配置文件怎么写

**Comment by richardchien** [comment]
> 我们在访问 ip:9000 端口的时候，输入密码提示【链接被拒绝：Authentication failure】

这是 noVNC 密码，应该填 docker 运行环境变量的 `VNC_PASSWD` 值，参考 [这里](https://cqhttp.cc/docs/4.15/#/Docker?id=%E9%80%9A%E8%BF%87%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E9%85%8D%E7%BD%AE%E5%AE%B9%E5%99%A8%E7%9A%84%E8%BF%90%E8%A1%8C)
