### ISSUE TITLE
有没有什么办法发送本地文件到qq群或者qq好友吗？

### ISSUE THREAD

**Issue by Brief-rf** [richardchien/coolq-http-api#354]
我做了一个青年大学习统计的功能，就差最后一步将文件发送给团支书了

**Comment by ExerciseBook** [comment]
@Brief-rf 没 酷Q 不支持发文件，但是你可以曲线救国一下。指发一个 http 地址。

**Comment by Brief-rf** [comment]
想到发送到一个网址，不过团支书又要下载了，所以我还是手动发送吧^_^

**Comment by aboutmydreams** [comment]
如果可以收的话就能打个包发了

**Comment by Brief-rf** [comment]
> 如果可以收的话就能打个包发了
是的，打包做好了，就差发送了
