### ISSUE TITLE
群发问题，图片文字，时而能收到时而收不到

### ISSUE THREAD

**Issue by dheiniu** [richardchien/coolq-http-api#355]
我发了一串文字，能收到
发了三张图片，收到2张
发送文字+图片，不能收到

图片（base64）

且，在酷Q那边均返回发送正常状态，该账号正常状态腾讯那边未封禁

还有个问题，发送字符有长度限制嘛，限制是多少

**Comment by ExerciseBook** [comment]
1. 酷Q没作限制
2. 此行为违反酷Q EULA，建议自己再斟酌一下你的这个功能是否会骚扰到其他人。
![image](https://user-images.githubusercontent.com/6327311/88050252-0e5aa100-cb89-11ea-8b5a-1d8180e6fb0b.png)
