### ISSUE TITLE
go-cqhttp

### ISSUE THREAD

**Issue by Mrs4s** [richardchien/coolq-http-api#356]
cqhttp golang原生实现
https://github.com/Mrs4s/go-cqhttp
希望增加到  相似项目 列表, 感谢.

**Comment by ExerciseBook** [comment]
先star了

**Comment by Ink-33** [comment]
先star了

**Comment by ExerciseBook** [comment]
https://github.com/richardchien/coolq-http-api/issues/8
提一个。

**Comment by Mrs4s** [comment]
> #8
> 提一个。

暂时不会考虑另起炉灶做一套RESTful接口，因为现有基于cqhttp的sdk都无法兼容，目前我是在cqhttp接口的基础上做了一些拓展以实现新功能。

**Comment by richardchien** [comment]
已加
