### ISSUE TITLE
发送群消息时怎么主动艾特别人---求助

### ISSUE THREAD

**Issue by tm2018** [richardchien/coolq-http-api#359]
大佬好:

代码如下：
bot = nonebot.get_bot()
await bot.send_group_msg(group_id=xxxx, message=msg)

如上，我想实现发送群消息时，主动去艾特某个user，但是nonebot.get_bot()方法里面send_msg send_group_msg等方法未发现其支持艾特的功能；
尝试用cq码发送，如下,但是接收到的消息只是字符串：
await bot.send_group_msg(group_id=xxxx, message='[CQ=at,qq=1111111]----测试',auto_escape=False)

希望能得到帮助，感谢。

**Comment by Ink-33** [comment]
试试改用双引号

**Comment by tm2018** [comment]
> 试试改用双引号

试过了，还是不行

**Comment by ExerciseBook** [comment]
https://docs.cqp.im/manual/cqcode/

建议使用复制粘贴

```
[CQ:at,qq=114514]
```

**Comment by Ink-33** [comment]
> > 试试改用双引号
> 
> 试过了，还是不行

你CQ码错了[CQ:at,qq=114514]，是冒号不是等于

**Comment by tm2018** [comment]
> > > 试试改用双引号
> > 
> > 
> > 试过了，还是不行
> 
> 你CQ码错了[CQ:at,qq=114514]，是冒号不是等于

/gg  谢谢大佬，也谢谢楼上各位大佬

**Comment by ExerciseBook** [comment]
不客气~

**Comment by ExerciseBook** [comment]
你是打算做QQ群外榜播报吗X

**Comment by tm2018** [comment]
> 你是打算做QQ群外榜播报吗X

森马鬼  PS：我是良民

**Comment by ExerciseBook** [comment]
@tm2018 我看你 fork 了个青岛大学oj，我就猜你想做外榜播报 😂
