### ISSUE TITLE
API更新了撤回

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [richardchien/coolq-http-api#37]
https://d.cqp.me/Pro/%E5%BC%80%E5%8F%91/V9%E6%9B%B4%E6%96%B0%E8%87%B3V9%2B

我本来准备更新下cqsocketapi，结果发现坑太多了，于是准备把我的项目迁移到http-api

您这个项目完善太多了，刚刚读了半天感觉写的很强大，赞！

**Comment by richardchien** [comment]
谢谢支持，插件最新版（3.3.1）已经更新了酷 Q 的新功能
