### ISSUE TITLE
针对Pro版本发送图片的问题

### ISSUE THREAD

**Issue by lzf0112** [richardchien/coolq-http-api#4]
Hi，谢谢你提供的插件，个人感觉很实用。

但是在使用过程中有个小问题，不知能否有空帮忙完善下：
现在CoolQ 发送图片的时候只能发送本地图片，能否增加个功能支持发送网络图片（直接提供个图片地址），定义特殊格式，当遇到网络图片时先下载到本地指定文件夹，然后发送再删除图片。

不知这样能否可行？

**Comment by richardchien** [comment]
因为我一开始开发的时候是尽量让 HTTP 接口和酷 Q 的 C++ 接口相似，所以没有对 CQ 码的不同功能做分别处理，你这个需求需要把发送图片的 CQ 码的功能分离出来作为一个单独的接口，我还要再权衡一下这个怎么做比较好，暂时建议你先在自己的插件里面下载到酷 Q 那个 image 文件夹

**Comment by richardchien** [comment]
OK，我采用了直接修改 CQ 码的方法，已经可以发网络图了，在这个 release，https://github.com/richardchien/coolq-http-api/releases/tag/v1.0.2

**Comment by lzf0112** [comment]
谢谢修改。但是有个问题：现在一条消息只能发送图片或者文字，是否可支持对图文形式的处理（即一条消息既有图片又有文字的）。

**Comment by richardchien** [comment]
这可以的，CQ 码本来就支持，你可以直接 `[CQ:image,file=1.jpg] test [CQ:image,file=2.jpg]` 这样发出来是两个图中间是 `test`。不过似乎有些比较复杂的图文，酷 Q 自己会拆分。

**Comment by lzf0112** [comment]
不清楚是哪个环节的问题：[CQ:image,file=1.jpg] test [CQ:image,file=2.jpg] 可以发送成功，如果是[CQ:image,file=1.jpg] test 就只收到图片没文字。

**Comment by richardchien** [comment]
卧槽，好吧我觉得这可能又是我的 bug……容我看看

**Comment by richardchien** [comment]
抱歉啊，是我的问题，修复了，[v1.0.2 build 6](https://github.com/richardchien/coolq-http-api/releases/tag/v1.0.2b6)，这次应该没什么问题了，如果还遇到其它问题也欢迎继续反馈。

**Comment by lzf0112** [comment]
可以了，谢谢哥们。
