### ISSUE TITLE
反向websocket，当服务器主动断开后，客户端不会再重连

### ISSUE THREAD

**Issue by yangjinhe** [richardchien/coolq-http-api#40]
如题，刚刚我在做测试的时候发现，如果是服务器挂了，反向websocket会默认3秒去重连一次，如果服务器主动调用close方法，客户端没有再尝试重连。

**Comment by richardchien** [comment]
就是这样设定的，如果服务器通过状态码 1000 来关闭链接，就不会重连

**Comment by yangjinhe** [comment]
原来如此
