### ISSUE TITLE
请问为什么去掉了pattern配置项？

### ISSUE THREAD

**Issue by cegehiku** [richardchien/coolq-http-api#43]
我看提交记录以前是可以过滤上报事件以减轻服务器压力的，现在为什么去掉了这个功能？是出于什么考虑吗？

#18

**Comment by richardchien** [comment]
因为实际使用中更多的过滤其实应该是对好友、群、讨论组的过滤，而不是对消息的过滤，原先那个 `pattern` 配置实际意义不是非常大（如果只是单个酷 Q 客户端，一般的后端事实上都不会产生太大的压力，只需要后端在收到请求时及时过滤掉无用消息就行），当然 3.x 版本移除了这个配置也有一定冲动成分。

后来有用户提到有很多客户端往一个后端上报的情况，这个确实存在问题，所以我也在考虑新的事件过滤方式，等后面有空可能会重新加上过滤功能。

**Comment by richardchien** [comment]
我新开了个 issue 来讨论过滤这个问题 #44

**Comment by cegehiku** [comment]
了解，非常感谢。
