### ISSUE TITLE
Amanda机器人是否可以适配

### ISSUE THREAD

**Issue by LiuYuLu** [richardchien/coolq-http-api#45]
首先得感谢大佬做了一个这么好的插件。    

最近在网上看到一个新的amanda机器人，界面和酷Q神似，不知道是否会进行适配？

**Comment by TwilightHome** [comment]
amanda好像用的pc协议,用过,不错

**Comment by imlida** [comment]
同求，酷q机器人的移动端协议由于分段发送的机制会出现链接被截断的问题

**Comment by tsztodd** [comment]
同求

**Comment by richardchien** [comment]
由于精力有限，可能 Amanda 或其它机器人适配应该是不太能做了，不过现在它们各自应该也都有不错的 HTTP 插件了吧
