### ISSUE TITLE
385错误 消息不支持或为空

### ISSUE THREAD

**Issue by shiwzhi** [richardchien/coolq-http-api#5]
payload = {'group_id': id, 'message': message, 'is_raw': False}

r = requests.post(url, json=payload)

is_raw 为True时可以正常发送

**Comment by richardchien** [comment]
可以发一下你的消息内容吗

**Comment by richardchien** [comment]
我知道了，我的锅，加了增强 CQ 码结果正常消息出问题了

**Comment by richardchien** [comment]
已修复，请更新最新的 release，https://github.com/richardchien/coolq-http-api/releases/tag/v1.0.2b5

**Comment by richardchien** [comment]
之前的修复版本产生了新的 bug，[v1.0.2 build 6](https://github.com/richardchien/coolq-http-api/releases/tag/v1.0.2b6) 这个版本应该基本上完全修复这个问题了。
