### ISSUE TITLE
设置 post_url的timeout方法

### ISSUE THREAD

**Issue by Evense-Lian** [richardchien/coolq-http-api#53]
请问下 ，，post_ur 的超时时间能设置吗

**Comment by richardchien** [comment]
我考虑下吧

**Comment by Evense-Lian** [comment]
像着用等待时间过长的方法。我可以用其他方法替代吗。。反向stocket能满足吗。。

**Comment by richardchien** [comment]
具体使用情景是什么样

**Comment by Evense-Lian** [comment]
具体情况是post超时了。。就是有一条链接消息发过来，记录到数据库，，然后有一个客户端exe的程序挂在本地机器上采集链接上对应的一些消息，然后返回给qq，（在执行返回的过程中这里会需要一些时间，有时候是大于30秒的时间，这样会超时处理），stocket不是很了解，早上试了下，貌似也不能满足要求，现在发现你这个工具会开一个本地api给远程调用，现在可以做异步线程执行返回结果处理调用api也能满足需求，现在就是想@指定的qq不知道怎么@    是发送群消息@指定的qq

**Comment by richardchien** [comment]
对，你这个需求应该等客户端程序采集完后单独调 API 发送消息的。



> @指定的qq

这个就是用 CQ 码，对应文本就是

```
[CQ:at,qq=12345]
```

如果是发送数组格式的，就是

```json
[
    {
        "type": "at",
        "data": {"id": "12345"}
    }
]
```
