### ISSUE TITLE
ws_reverse或者http_post上报，消息体内加qq号，便于多实例时服务端区分是哪个实例的消息

### ISSUE THREAD

**Issue by soloph** [richardchien/coolq-http-api#55]
对于ws_reverse， 在和服务端建立连接的时候应带上实例信息等参数（或者连接成功之后，发一条标识自己身份的消息，用于服务端存储key）
后续服务端向插件回复消息的时候就可以通过key来区分发给哪个实例了

**Comment by richardchien** [comment]
直接在消息体加了，代码改动少一些，下个版本发
