### ISSUE TITLE
是否有可能将HTTP API插件生成的消息作为事件上报？

### ISSUE THREAD

**Issue by zmwangx** [richardchien/coolq-http-api#57]
目前我使用CoolQ HTTP API的事件上报功能记录群聊历史。由于针对事件的回复以及直接调用API生成的消息（如`/send_group_msg`）不会产生新的事件，所以日志中会缺少机器人的消息；尤其是后者，由于`/send_group_msg`一般是在独立于事件处理服务的程序中调用的，所以除非在事件处理服务中加个中介接口，否则跨程序写日志比较麻烦。另外，我也有一些机器人连环触发的构想，在当前HTTP API生成的消息不上报的条件下，实现起来也略复杂。

请问是否有可能上报HTTP API生成的消息？（可以默认不上报，只要有个选项就行。）

注：我没看过酷Q本身的API，所以如果明显支持不了，或者很复杂的话，请见谅。

**Comment by richardchien** [comment]
实际上酷 Q 本身就不会对自己发送的消息产生事件，也不会上报自己账号在其它客户端发送的消息，所以如果在插件里做你说的这个功能的话，其实跟你在后端写，复杂程度是一样的，而且由于收不到自己在其它客户端发的消息，而且发送消息有时候会失败，这样就会有点奇怪

**Comment by zmwangx** [comment]
唉，跟我猜得一样。谢谢答疑。
