### ISSUE TITLE
事件队列被部分应用堵塞问题

### ISSUE THREAD

**Issue by miaozhongtao** [richardchien/coolq-http-api#59]
我只开了这个http api插件，酷Q运行一段时间就会报事件队列被部分应用堵塞，事件接收已暂停。
![image](https://user-images.githubusercontent.com/25563020/38348366-ed97d644-38d3-11e8-9bd7-ca4d79f9c78e.png)
这是怎么回事呢？

**Comment by miaozhongtao** [comment]
![image](https://user-images.githubusercontent.com/25563020/38348491-bb9a1e6c-38d4-11e8-9dd8-513688c3c8bd.png)

**Comment by miaozhongtao** [comment]
懒得打码了orz

**Comment by richardchien** [comment]
左下角改成 Debug 看下

**Comment by miaozhongtao** [comment]
![111](https://user-images.githubusercontent.com/25563020/38348559-2d53b342-38d5-11e8-8e7b-cd8646c95767.png)

**Comment by miaozhongtao** [comment]
好吧 我再看看我的代码。多谢
