### ISSUE TITLE
发送语音总是返回-11错误

### ISSUE THREAD

**Issue by rikakomoe** [richardchien/coolq-http-api#63]
{"data":null,"retcode":-11,"status":"failed"}

运行的是酷Q Pro图灵版
不知是酷Q的问题还是插件这边的问题
可否帮忙看下

**Comment by richardchien** [comment]
多半是没有装语音组件

**Comment by rikakomoe** [comment]
语音组件是什么
我用的是 richardchien/cqhttp 的 docker，文档里好像没看到提及语音组件的问题？

**Comment by richardchien** [comment]
酷Q Pro 发送语音需要下一些另外的 dll 进去，看这个 https://cqp.cc/forum.php?mod=viewthread&tid=21132&highlight=%E8%AF%AD%E9%9F%B3%E7%BB%84%E4%BB%B6

**Comment by rikakomoe** [comment]
已解决，感谢！
也许可以在文档里提及一下？

**Comment by richardchien** [comment]
确实，下次更新文档加上吧
