### ISSUE TITLE
reverse ws API稳定性？

### ISSUE THREAD

**Issue by suitool** [richardchien/coolq-http-api#64]
在同一台机器上，通过docker/wine运行cqa及coolq-http-api插件， 配置ws_api连接host机器上的ws service。

coolq-http-api能开启与ws的连接，但event接口更稳定，api接口常常是能连接，给该接口发送消息也能接收，但不响应（从没有通讯层异常判断消息已接收）。

注：我们在一个docker环境下运行多个CQA。有时这些CQA的的coolq-http-api插件都正常工作，有时候部分正常工作。我们启动CQA的方式是每30秒启动一个，最大不超过10个

**Comment by richardchien** [comment]
> api接口常常是能连接，给该接口发送消息也能接收，但不响应（从没有通讯层异常判断消息已接收）

那实际调用执行到了吗，比如消息是不是确实发出去了呢，另外看下 Debug 级别的日志？

**Comment by suitool** [comment]
![default](https://user-images.githubusercontent.com/32243529/40300456-dbe5df06-5d1b-11e8-9e82-5034f83c388d.png)
截图说明 ：
从09:22起，我重启了websocket服务器（使用了tornado websocket，并不清楚这种情况下是否会发1000），这里websocket event能感知并重新连接，且连接成功，但api client似乎并不知道断开了，或者很久之前就断开了？但没有主动连接。希望两个接口的行为能一致。

参数：
![default](https://user-images.githubusercontent.com/32243529/40300573-37358668-5d1c-11e8-83be-ed6dff7503bd.png)

**Comment by richardchien** [comment]
从你的日志来看，API 断开后重连了然后并没有再次断开啊，看起来没有问题

**Comment by suitool** [comment]
中间服务器经过了一次重启（09：22），所以这些连接必然是断开了。只是Event能检测到连接断开，并重新连接，但是从09：22起，并没有api检测到连接断开并重启的日志.
今天类似情况又发生一次，无论如何重启docker，重启服务器，重启cqa都无济于事，最后我在cqa已经启动完成的情况下，重启插件，两个QQ号一个瞬间连接上并正常工作，另一个第二次重启时正常工作。

有什么办法可以进一步打开coolq-http的日志？
这会是一个最新的cqa版本与3.4的coolq-http之间的问题吗？

**Comment by suitool** [comment]
我的猜测是，由于插件先于CQA初始化完成，此时还没拿到登录信息，此时发给插件的get_login_info就不会响应。

我方服务器逻辑是：
asynn def open():
    #等待连接，并发一个get_login_info的请求
def on_get_login_info:
   # save account, bind the hander to this account, we call it session
   # send get_status peridically, every 15s

**Comment by richardchien** [comment]
在配置文件里设置 `ws_reverse_reconnect_on_code_1000` 为 `yes` 试试

**Comment by suitool** [comment]
这个配置是这样设置的：

![default](https://user-images.githubusercontent.com/32243529/40575624-e7200a1a-611a-11e8-985c-cc90c5335e2c.png)

**Comment by suitool** [comment]
好的，我需要整理一下，去除不必要的依赖后再给你。

**Comment by richardchien** [comment]
好的麻烦了

**Comment by suitool** [comment]
![default](https://user-images.githubusercontent.com/32243529/40953260-7ff60f80-68b1-11e8-92a3-aa25c08b3cfd.png)

**Comment by suitool** [comment]
![default](https://user-images.githubusercontent.com/32243529/40960519-8ce59096-68d2-11e8-89ad-a5118511b157.png)

**Comment by suitool** [comment]
![default](https://user-images.githubusercontent.com/32243529/40968723-d72fee74-68e8-11e8-9f9f-c324ff17b19f.png)

**Comment by suitool** [comment]
4.0.5经测试，很稳定。断了以后可以自动重连。
测试共使用了约40个容器，每个容器10个QQ
