### ISSUE TITLE
文档中的配置页面404

### ISSUE THREAD

**Issue by hsluoyz** [richardchien/coolq-http-api#65]
https://cqhttp.cc/docs/3.4/#/?id=%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

这里：

```
启用后插件将开启一个 HTTP 服务器来接收请求，默认监听 0.0.0.0:5700，首次启用会生成一个默认配置文件，在酷 Q app 文件夹的 io.github.richardchien.coolqhttpapi 文件夹中，文件名 config.cfg，使用 ini 格式填写。关于配置项的说明，见 配置。
```

最后的``配置``链接打开是404：https://cqhttp.cc/Configuration

![image](https://user-images.githubusercontent.com/3787410/40286620-c6fa14cc-5cda-11e8-9227-14529c6ffbcc.png)

**Comment by richardchien** [comment]
诶，我这边可以。你用的什么浏览器，有可能因为禁用了 JS 或者 JS 没加载好

**Comment by hsluoyz** [comment]
发现原因了。我是用``右键``->``在新窗口中打开链接`，这样打开就会404。直接左键点击就没事。这个链接不支持右键打开。

**Comment by richardchien** [comment]
因为这个是单页应用，我用的那个文档框架好像就是会这样，我回头看下吧，不一定能搞

**Comment by richardchien** [comment]
感谢 @rikakomoe 给 [egoist/docute](https://github.com/egoist/docute) 项目贡献了 fix，感谢 docute 很快发了新版，这个问题已经解决了

**Comment by hsluoyz** [comment]
谢谢 👍
