### ISSUE TITLE
air版本，用了docker2的镜像，经常出现报错

### ISSUE THREAD

**Issue by mlsjla** [richardchien/coolq-http-api#66]
<img width="576" alt="kuq" src="https://user-images.githubusercontent.com/9654331/40618476-2a263870-62c4-11e8-8ed3-582de875757a.png">

**Comment by richardchien** [comment]
你是用的官方镜像然后安装的插件吗，还是用的我做好的镜像，另外请提供一下出错前酷Q的 debug 级别的日志

**Comment by mlsjla** [comment]
@richardchien  

我用了https://cqp.cc/t/34558 docker镜像

关于日志，不清楚哪里开启。也没找到日志。

我估计可能和air被阉割语音图片之类原因有关。

**Comment by richardchien** [comment]
你用的是插件哪个版本

mlsjla <notifications@github.com>于2018年5月29日 周二11:05写道：

**Comment by mlsjla** [comment]
@richardchien  就这个，http上报组件。
io.github.richardchien.coolqhttpapi

感觉用air版本的时候， 容易出现上面截图问题。 pro版本暂时没有测试。

**Comment by richardchien** [comment]
我是说这个插件的版本号（，可以在酷 Q 的应用菜单里面看到

**Comment by mlsjla** [comment]
<img width="689" alt="ku-1" src="https://user-images.githubusercontent.com/9654331/40639801-7923b08e-6345-11e8-9ba8-4e964430c7ad.png">

**Comment by richardchien** [comment]
首先更新到 alpha.4 版本试试，或者降到 3.4.0，如果是 4.0.0 的话，看下酷 Q 主目录的 `app/io.github.richardchien.coolqhttpapi/log` 里面的日志文件的内容，看下报错前发生了什么

**Comment by richardchien** [comment]
我试了下，这个应该是因为 alpha 版和 docker 兼容性还没做好，你先换到 3.4.0 吧

**Comment by richardchien** [comment]
测试了一下发现 4.0.0 alpha 版本在 Docker 容器内多次调用发送图片（实际会失败），就会出现这个报错。3.4.0 版本和 Windows 环境有待测试，目前不清楚是插件问题还是酷 Q 问题。

**Comment by richardchien** [comment]
今天又测试了一下 4.0.0-beta.2 发现复现不出来了……有可能酷 Q 更新修复了？先 close 了，如果后面还遇到的话，再 reopen 吧

**Comment by richardchien** [comment]
[v4.0.2](https://github.com/richardchien/coolq-http-api/releases/tag/v4.0.2) 应该修复了这个问题
