### ISSUE TITLE
增加群信息接口

### ISSUE THREAD

**Issue by suitool** [richardchien/coolq-http-api#67]
现在群只有get_group_list和get_group_member_list, get_group_member_info这几个接口，如果需要知道群简介、群容量和群当前人数则拿不到，能否增加一个get_group_info的接口？

**Comment by richardchien** [comment]
这个不确定能不能有，酷 Q 原生接口是没有的，不知道酷 Q 提供的 cookie 能不能用来取，后面有空看看

**Comment by richardchien** [comment]
[v4.0.1](https://github.com/richardchien/coolq-http-api/releases/tag/v4.0.1) 已加入

**Comment by suitool** [comment]
非常感谢！
