### ISSUE TITLE
README.md中添加另一个应用实例

### ISSUE THREAD

**Issue by LovelyA72** [richardchien/coolq-http-api#68]
这个应用是基于kj大佬的kjBot框架的，叫做[YeziiBot](https://github.com/LovelyA72/YeziiBot)，是一个PHP bot.

**Comment by richardchien** [comment]
简介写什么呢

**Comment by LovelyA72** [comment]
内置一定实例的PHP QQbot快速开发框架（其实那些实例已经可以当成品用了）

**Comment by richardchien** [comment]
OK 加上了
