### ISSUE TITLE
酷Q Air 升级 coolq-http-api v4.0.1 后QQ群禁言失效

### ISSUE THREAD

**Issue by simple4wan** [richardchien/coolq-http-api#70]
<img width="362" alt="qq20180611-110819 2x" src="https://user-images.githubusercontent.com/12567219/41211077-cf206d66-6d67-11e8-895e-8e4603a8777e.png">
酷Q Air 版本  5.11.14A (180531)
收到群消息后响应数据 {"block": true, "reply": "请勿违反群规", "delete": true, "ban": true}

**Comment by richardchien** [comment]
似乎和 #66 是类似的问题，还需要详细研究

**Comment by richardchien** [comment]
[v4.0.2](https://github.com/richardchien/coolq-http-api/releases/tag/v4.0.2) 修复了这个问题
