### ISSUE TITLE
CONFIG_MANUALLY的缺省值应该为true

### ISSUE THREAD

**Issue by suitool** [richardchien/coolq-http-api#71]
容器一旦创建，环境变量就不容易修改。如果用户手动设置了配置文件的话，一般是希望去overwrite这个很久以前创建容器时的配置（比如url发生了变化），而不是反过来。

当前CONFIG_MANUALLY设置为false，因此如果容器不变，升级到4.0后，仍然无法获得修改容器环境变量的权利。

**Comment by suitool** [comment]
建议各配置项的优先级及merge顺序：
1. 系统的环境变量 （优先最低，因为可能使用场景是容器，而容器的环境变量修改较困难）
2. config.json, 通用配置项，即全体qq都会用到的配置项
3. %qq_number%.json。

在merge时，先将1读入内存，如果2中有同样的键值，则overwrite 1，2与1的合并完成。
再将合并的结果与3合并，方法同上。

合并后的配置通过log输出，但并不写盘。这个过程中不要修改上述1，2，3中的任何一项。

**Comment by richardchien** [comment]
4.0.3 版的镜像是改成默认允许修改了
