### ISSUE TITLE
file size of log file?

### ISSUE THREAD

**Issue by suitool** [richardchien/coolq-http-api#77]
size of log file for each qq has exceeded 5M but still not rotated/cleaned.

Questions:
1. have coolq-http-api implemented rotating log file?
2. when will log file been cleaned?
3. If we (external operator) clean these files, should we restart CQA/coolq-http-api?

**Comment by richardchien** [comment]
The max log file size is set to 6MB in code, and when the size of log file reaches the max size, it rotates. Currently the log files won't be automatically cleaned. If you want to clean those files, you should stop CoolQ first (or just disable the HTTP API plugin).

**Comment by richardchien** [comment]
I've added an API (`/clean_plugin_log`) to clean cqhttp log file in [v4.1.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.1.0), so you are no longer required to stop CoolQ to clean those log files.

**Comment by suitool** [comment]
seems to me it's better to add configuration in order to customize behaviour:
1. maxBytes
2. maxBackupCount
3. logLevel

just like python logging and RotatingFileHandler

**Comment by richardchien** [comment]
As far as I see, it can be done. I will look at it next week. What about starting a new issue to track that?

**Comment by suitool** [comment]
closed this one as #79 is opened for tracking the new feature request
