### ISSUE TITLE
[Feature Request] group size in _get_group_info API

### ISSUE THREAD

**Issue by suitool** [richardchien/coolq-http-api#78]
Currently we got these info from _get_group_info API, which is introduced since 4.0:

group_id | number | 群号
-- | -- | --
group_name | string | 群名称
create_time | number | 创建时间
category | number | 群分类，具体这个 ID 对应的名称暂时没有
member_count | number | 成员数
introduction | string | 群介绍
admins | array | 群主和管理员列表

is it possible to provide group size (capacity of the group, like 200, 500, 1000, 2000, 5000)?

**Comment by richardchien** [comment]
[v4.3.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.3.0) fixes this
