### ISSUE TITLE
logging behaviour

### ISSUE THREAD

**Issue by suitool** [richardchien/coolq-http-api#79]
seems to me it's better to add configuration in order to customize behaviour:

    maxBytes, default is 10M
    maxBackupCount, default is 7
    logLevel, default value is warning, due to at most occasions, we can assume coolq-http-api work as expected and no need to check log

just like python logging and RotatingFileHandler

**Comment by richardchien** [comment]
[v4.2.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.2.0) 加上了这些配置
