### ISSUE TITLE
[Feature Request] require qq level info from get_stranger_info

### ISSUE THREAD

**Issue by suitool** [richardchien/coolq-http-api#80]
currently get_stranger_info returns:

字段名 | 数据类型 | 说明
-- | -- | --
user_id | number | QQ 号
nickname | string | 昵称
sex | string | 性别，male 或 female 或 unknown
age | number | 年龄

is it possible to return qq_level as well? group moderator need use qq_level to decide if he should allow/disallow the group join applicant.

Just in case this info is returned by CQA but be omitted by coolq-http-api

**Comment by richardchien** [comment]
next version will add this
