### ISSUE TITLE
[SDK] node-cq-websocket 已兼容至 CoolQ HTTP API 4.x

### ISSUE THREAD

**Issue by momocow** [richardchien/coolq-http-api#89]
SDK 已更新。
自 node-cq-websocket v1.3.0 開始, 兼容 CoolQ HTTP API 3.x 及 4.x。

**Comment by momocow** [comment]
相關測試沒有做很多。

主要就是字段 `event` => `notice` 的修改, 新增了對 `request` 及 `notice` 兩種事件的細節處理。

若有問題, 歡迎大家[到這發 Issue](https://github.com/momocow/node-cq-websocket/issues)。

**Comment by richardchien** [comment]
OK，README 改好了，感谢贡献
