### ISSUE TITLE
收到群里其他人发送的私聊信息时，可否把群号也上报

### ISSUE THREAD

**Issue by sxyandapp** [richardchien/coolq-http-api#9]
收到群里其他人发送的私聊信息时，可否把群号也上报。我在cuq的日志里可以看到私聊消息是有群号的，但是作者的api接口里把群号省略了，可否把这个群号一同上报，这样当别人通过群发送私聊信息时，就能判断对方是通过哪个群发送的私聊信息了

**Comment by richardchien** [comment]
这个似乎是不行的，见 [https://github.com/richardchien/coolq-http-api/blob/master/src/appmain.cpp#L277](https://github.com/richardchien/coolq-http-api/blob/master/src/appmain.cpp#L277)，酷 Q 这个事件的参数，只有 `sub_type` 标记了是来自哪里，没有其它参数标记来源的群号，所以我也没有办法了，[酷Q来自群的临时消息无法得知来源群](https://cqp.cc/forum.php?mod=viewthread&tid=30779&highlight=%E4%B8%B4%E6%97%B6%E6%B6%88%E6%81%AF%2B%E7%BE%A4) 这个帖子下面版主回复也确认了。

**Comment by sxyandapp** [comment]
那有没有接口可以获取某个群的成员列表呢？如果有的话我可以通过遍历所有群的成员列表从而间接判断消息源的qq属于哪个群

**Comment by richardchien** [comment]
这个酷 Q 的 SDK 里没有，不过是有办法获取的，我打算在下一个版本加上，但现在还在考虑 API 的设计问题，因为现在这套 API 我是尽量让它接近酷 Q 的 SDK 的，所以可能会放在后面写的另一套 REST API 里。

获取群成员列表的方法就是通过 QQ 空间一个接口 `http://qun.qzone.qq.com/cgi-bin/get_group_member?callbackFun=_GroupMember&uin=QQ号&groupid=群号&neednum=1&g_tk=CsrfToken`，你如果急着用的话，可以先用现在插件里提供的 `get_cookies` 和 `get_csrf_token` 获取到 Cookie 和 token，然后去 GET 请求这个链接，替换一下里面的「QQ号」「群号」「CsrfToken」就行了。

**Comment by sxyandapp** [comment]
有空试试，谢谢楼主

**Comment by richardchien** [comment]
不客气，也谢谢你的支持了

**Comment by sxyandapp** [comment]
刚测试了，get_csrf_token和get_cookies两个接口都返回101，酷q没有打印任何日志，难道是因为我的是酷q免费版？

**Comment by sxyandapp** [comment]
好吧，刚把cpk升级成最新版就能获取了。。。。囧

**Comment by richardchien** [comment]
嗯……一定要用最新版
