### ISSUE TITLE
`set_restart` 接口的 `clean_cache` 参数导致重启后无法快速登录

### ISSUE THREAD

**Issue by richardchien** [richardchien/coolq-http-api#95]

**Comment by richardchien** [comment]
v4.3.1 暂时禁用了 `clean_cache` 参数，转而提供了 `clean_log` 参数用于单独清除日志数据库

**Comment by lipa10** [comment]
试了一下，现在可以清空logv1.db了，但另外一个较大的eventv2.db并没有清空，希望把这个也加进清空列表

或者像/clean_data_dir接口一样允许输入文件名自己选择要清空的数据库吧，根据观察某些情况下cache.db也会变大

**Comment by richardchien** [comment]
@lipa10 我下周考虑下

**Comment by richardchien** [comment]
[v4.4.0](https://github.com/richardchien/coolq-http-api/releases/tag/v4.4.0) 加入了，并且 `clean_cache` 参数的意义已经修改，这个 issue 先关了
